const MOCK_TREES = [
  {
    id: "t1",
    code: "ARX-NH-004821",
    species: "Neem (Azadirachta indica)",
    project: "NHAI KM-48 Greenbelt",
    workArea: "Chainage 142–148",
    health: "good",
    sync: "synced",
    verified: true,
    photo:
      "https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?w=400&h=400&fit=crop",
    lat: 26.9124,
    lng: 75.7873,
  },
  {
    id: "t2",
    code: "ARX-NH-004822",
    species: "Khejri",
    project: "NHAI KM-48 Greenbelt",
    workArea: "Chainage 142–148",
    health: "stressed",
    sync: "pending",
    verified: false,
    photo:
      "https://images.unsplash.com/photo-1513836279014-a89f9a76ae07?w=400&h=400&fit=crop",
    lat: 26.9131,
    lng: 75.7881,
  },
  {
    id: "t3",
    code: "ARX-CA-009104",
    species: "Unidentified",
    project: "CAMPA Block A",
    workArea: "Compartment 3",
    health: "unknown",
    sync: "failed",
    verified: false,
    photo: null,
    lat: 27.0234,
    lng: 74.5521,
  },
  {
    id: "t4",
    code: "ARX-CA-009105",
    species: "Babul",
    project: "CAMPA Block A",
    workArea: "Compartment 3",
    health: "good",
    sync: "synced",
    verified: true,
    photo:
      "https://images.unsplash.com/photo-1465146633011-14f8e0781093?w=400&h=400&fit=crop",
    lat: 27.0240,
    lng: 74.5530,
  },
  {
    id: "t5",
    code: "ARX-NV-000312",
    species: "Pilkhan",
    project: "Nagar Van Phase 2",
    workArea: "Zone B",
    health: "good",
    sync: "synced",
    verified: true,
    photo:
      "https://images.unsplash.com/photo-1598902108854-10e335adac99?w=400&h=400&fit=crop",
    lat: 28.6139,
    lng: 77.209,
  },
  {
    id: "t6",
    code: "ARX-NV-000313",
    species: "Jamun",
    project: "Nagar Van Phase 2",
    workArea: "Zone B",
    health: "at_risk",
    sync: "synced",
    verified: true,
    photo:
      "https://images.unsplash.com/photo-1502082553048-f009c37126b9?w=400&h=400&fit=crop",
    lat: 28.6145,
    lng: 77.2102,
  },
];

const MOCK_ALERTS = [
  {
    id: "a1",
    severity: "critical",
    title: "Acute NDVI drop detected",
    context: "NHAI KM-48 · Chainage 142–148",
    time: "2h ago",
    action: "Inspect site",
    kind: "ndvi_acute_drop",
    body:
      "NDVI fell 0.18 vs 30-day baseline. Cloud cover 8%. Recommend field inspection within 48h.",
  },
  {
    id: "a2",
    severity: "high",
    title: "Fire watch — active detections nearby",
    context: "CAMPA Block A · 12 km NE",
    time: "5h ago",
    action: "View on map",
    kind: "fire_alert",
    body: "3 VIIRS detections within 25 km radius. Seasonal risk elevated.",
  },
  {
    id: "a3",
    severity: "medium",
    title: "Survival survey due",
    context: "12 trees · Nagar Van Phase 2",
    time: "1d ago",
    action: "Start surveys",
    kind: "survival_survey",
    body: "Trees planted 90 days ago require survival status update.",
  },
  {
    id: "a4",
    severity: "low",
    title: "SAR integrity aligned",
    context: "NHAI KM-48 · All work areas",
    time: "3d ago",
    action: "View monitoring",
    kind: "sar_integrity_drop",
    body: "Monthly SAR sweep completed. No divergence detected.",
  },
];

const MOCK_PROJECTS = [
  { id: "p1", name: "NHAI KM-48 Greenbelt", trees: 4821, segment: "Highway" },
  { id: "p2", name: "CAMPA Block A", trees: 9104, segment: "CAMPA" },
  { id: "p3", name: "Nagar Van Phase 2", trees: 312, segment: "Urban forest" },
];

const MOCK_MONITOR = [
  {
    site: "NHAI KM-48 · Ch. 142–148",
    ndvi: 0.52,
    trend: "down",
    action: "Field inspect",
    stale: false,
  },
  {
    site: "CAMPA Block A · Comp. 3",
    ndvi: 0.61,
    trend: "stable",
    action: "No action",
    stale: true,
  },
  {
    site: "Nagar Van · Zone B",
    ndvi: 0.48,
    trend: "down",
    action: "Review alerts",
    stale: false,
  },
];
