import type { MetadataRoute } from "next";

import { SITE_URL } from "@/lib/seo/site";

export default function robots(): MetadataRoute.Robots {
  return {
    rules: {
      userAgent: "*",
      allow: "/",
      disallow: [
        "/api/",
        "/auth",
        "/auth/",
        "/login",
        "/signup",
        "/onboarding",
        "/onboarding/",
        "/verify/",
        "/impact/",
        "/p/",
        "/dashboard",
        "/dashboard/",
        "/settings",
        "/settings/",
        "/platform",
        "/platform/",
        "/projects",
        "/projects/",
        "/intelligence",
        "/intelligence/",
        "/trees",
        "/trees/",
        "/satellite",
        "/satellite/",
        "/field-ops",
        "/field-ops/",
        "/monitoring",
        "/monitoring/",
        "/portfolio-health",
        "/portfolio-health/",
        "/bioacoustic",
        "/bioacoustic/",
        "/alerts",
        "/alerts/",
        "/assistant",
        "/assistant/",
        "/reports",
        "/reports/",
        "/map",
        "/map/",
        "/tools",
        "/tools/",
        "/verification",
        "/verification/",
        "/stewardship",
        "/stewardship/",
        "/presentation",
        "/presentationa",
      ],
    },
    sitemap: `${SITE_URL}/sitemap.xml`,
    host: SITE_URL,
  };
}
