#!/usr/bin/env python3
"""Generate cms-home-fallback.hi.json from English fallback with Hindi labels."""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "lib" / "cms-home-fallback.json"
DST = ROOT / "lib" / "cms-home-fallback.hi.json"

# User-visible string translations (English -> Hindi)
T = {
    "Platform": "प्लेटफ़ॉर्म",
    "Intelligence": "बुद्धिमत्ता",
    "Compliance": "अनुपालन",
    "Reports": "रिपोर्ट",
    "Programs": "कार्यक्रम",
    "How it works": "यह कैसे काम करता है",
    "Sign in": "साइन इन",
    "Get started": "शुरू करें",
    "India's environmental MRV platform — from citizen tree tagging to government-grade satellite fusion, bioacoustic biodiversity, and audit-ready compliance exports.": "भारत का पर्यावरण MRV प्लेटफ़ॉर्म — नागरिक पेड़ टैगिंग से सरकारी-स्तर उपग्रह फ्यूजन, जैव ध्वनि विविधता और ऑडिट-तैयार अनुपालन निर्यात तक।",
    "Intelligence for a thriving planet": "एक समृद्ध ग्रह के लिए बुद्धिमत्ता",
    "Executive dashboard": "कार्यकारी डैशबोर्ड",
    "Register a tree": "पेड़ पंजीकृत करें",
    "Field operations": "फील्ड कार्य",
    "Reports & exports": "रिपोर्ट और निर्यात",
    "BYOT citizen tagging": "BYOT नागरिक टैगिंग",
    "Government & NHAI": "सरकार और NHAI",
    "Corporate ESG": "कॉर्पोरेट ESG",
    "NGO & community": "NGO और समुदाय",
    "DPDP privacy controls": "DPDP गोपनीयता नियंत्रण",
    "BRSR & ISO exports": "BRSR और ISO निर्यात",
    "VM0047 checklists": "VM0047 चेकलिस्ट",
    "Audit evidence chain": "ऑडिट प्रमाण श्रृंखला",
    "Legal": "कानूनी",
    "Terms of Service": "सेवा की शर्तें",
    "Privacy Policy": "गोपनीयता नीति",
    "Data Use Policy": "डेटा उपयोग नीति",
    "Aranyix. All rights reserved.": "Aranyix. सर्वाधिकार सुरक्षित।",
    "MRV & audit-prep platform · Not a carbon credit issuer": "MRV और ऑडिट-तैयारी प्लेटफ़ॉर्म · कार्बन क्रेडिट जारीकर्ता नहीं",
    "Hero": "हीरो",
    "MRV · Compliance · Reporting": "MRV · अनुपालन · रिपोर्टिंग",
    "Environmental intelligence": "पर्यावरणीय बुद्धिमत्ता",
    "from field to audit room": "फील्ड से ऑडिट कक्ष तक",
    "Register trees on mobile, fuse NDVI with SAR integrity, score biodiversity with bioacoustics, and export BRSR, ISO 14064-2, TNFD, and VM0047 evidence — one platform for citizens, corporates, and government programs.": "मोबाइल पर पेड़ पंजीकृत करें, NDVI को SAR अखंडता के साथ जोड़ें, जैव ध्वनि से विविधता स्कोर करें, और BRSR, ISO 14064-2, TNFD और VM0047 प्रमाण निर्यात करें — नागरिकों, कॉर्पोरेट और सरकारी कार्यक्रमों के लिए एक प्लेटफ़ॉर्म।",
    "Framework mappings": "फ्रेमवर्क मैपिंग",
    "Indian languages": "भारतीय भाषाएँ",
    "Satellite fusion": "उपग्रह फ्यूजन",
    "Privacy controls": "गोपनीयता नियंत्रण",
    "Start free registration": "मुफ़्त पंजीकरण शुरू करें",
    "Explore the platform": "प्लेटफ़ॉर्म देखें",
    "Trust metrics": "विश्वास मेट्रिक",
    "Trees target scale": "पेड़ लक्ष्य स्केल",
    "Built for national programs": "राष्ट्रीय कार्यक्रमों के लिए",
    "Monitoring": "निगरानी",
    "Satellite + alert fusion": "उपग्रह + अलर्ट फ्यूजन",
    "Evidence chain": "प्रमाण श्रृंखला",
    "Tamper-evident audit trail": "छेड़छाड़-प्रूफ ऑडिट ट्रेल",
    "Field offline": "फील्ड ऑफ़लाइन",
    "Supervisor tree cache": "पर्यवेक्षक पेड़ कैश",
    "Platform capabilities": "प्लेटफ़ॉर्म क्षमताएँ",
    "Everything to monitor, prove, and report environmental impact": "पर्यावरण प्रभाव की निगरानी, प्रमाण और रिपोर्ट के लिए सब कुछ",
    "From a single citizen neem tree to million-tree portfolios — the same premium MRV stack for field teams, scientists, compliance officers, and board reviewers.": "एक नागरिक के नीम पेड़ से लेकर लाखों-पेड़ पोर्टफोलियो तक — फील्ड टीम, वैज्ञानिक, अनुपालन अधिकारी और बोर्ड समीक्षकों के लिए एक ही प्रीमियम MRV स्टैक।",
    "Tree MRV & passports": "पेड़ MRV और पासपोर्ट",
    "GPS registration, digital passports, QR codes, chainage for highways, and project setup wizards tuned to each scheme.": "GPS पंजीकरण, डिजिटल पासपोर्ट, QR कोड, राजमार्ग चेनेज, और प्रत्येक योजना के लिए प्रोजेक्ट सेटअप विज़ार्ड।",
    "Mobile field operations": "मोबाइल फील्ड कार्य",
    "Android field app with offline tree cache, photo capture, and register-next flows for high-volume planting drives.": "ऑफ़लाइन पेड़ कैश, फ़ोटो कैप्चर और उच्च-मात्रा रोपण के लिए register-next फ्लो वाला Android फील्ड ऐप।",
    "Satellite & SAR fusion": "उपग्रह और SAR फ्यूजन",
    "Sentinel NDVI health layers plus SAR integrity trends, fence validation, and portfolio threat dashboards.": "Sentinel NDVI स्वास्थ्य परतें, SAR अखंडता रुझान, बाड़ सत्यापन और पोर्टफोलियो खतरा डैशबोर्ड।",
    "Bioacoustic biodiversity": "जैव ध्वनि विविधता",
    "BirdNET-powered species detection, richness scoring, and habitat signals alongside planting evidence.": "BirdNET-संचालित प्रजाति पहचान, समृद्धि स्कोरिंग और रोपण प्रमाण के साथ आवास संकेत।",
    "AI intelligence layer": "AI बुद्धिमत्ता परत",
    "Species ID, health classification, executive summaries, and an in-app assistant for field and ops teams.": "प्रजाति ID, स्वास्थ्य वर्गीकरण, कार्यकारी सारांश और फील्ड/ऑप्स टीम के लिए इन-ऐप सहायक।",
    "Executive dashboards": "कार्यकारी डैशबोर्ड",
    "Portfolio health, carbon NPRT buffers, plot monitoring designs, and stratified sampling for verifier workflows.": "पोर्टफोलियो स्वास्थ्य, कार्बन NPRT बफर, प्लॉट निगरानी डिज़ाइन और सत्यापनकर्ता वर्कफ़्लो के लिए स्तरीकृत नमूनाकरण।",
    "Alerts & field actions": "अलर्ट और फील्ड कार्रवाई",
    "Canopy stress, mortality drift, fence breaches, and SAR anomalies routed to supervisors with verification loops.": "वनस्पति तनाव, मृत्यु विचलन, बाड़ उल्लंघन और SAR विसंगतियाँ पर्यवेक्षकों को सत्यापन लूप के साथ।",
    "Rule engine & schemes": "रूल इंजन और योजनाएँ",
    "Central scheme registry with NHAI, CAMPA, Nagar Van, and corporate templates — validation rules per program.": "NHAI, CAMPA, नगर वन और कॉर्पोरेट टेम्पलेट के साथ केंद्रीय योजना रजिस्ट्री — प्रति कार्यक्रम सत्यापन नियम।",
    "Intelligence pipeline": "बुद्धिमत्ता पाइपलाइन",
    "Intelligence stack": "बुद्धिमत्ता स्टैक",
    "Five layers. One audit-ready story.": "पाँच परतें। एक ऑडिट-तैयार कहानी।",
    "Field evidence, orbital signals, acoustic biodiversity, and AI fusion converge into signed exports your auditors and program officers can actually review.": "फील्ड प्रमाण, कक्षीय संकेत, ध्वनि विविधता और AI फ्यूजन हस्ताक्षरित निर्यात में — जिन्हें आपके ऑडिटर और अधिकारी समीक्षा कर सकें।",
    "Compliance & frameworks": "अनुपालन और फ्रेमवर्क",
    "Mapped to the standards your auditors already ask about": "उन मानकों से मैप जिनके बारे में ऑडिटर पहले से पूछते हैं",
    "Aranyix is an MRV and audit-preparation platform — not a carbon credit registry or legal certification body. We structure evidence so review conversations move faster.": "Aranyix MRV और ऑडिट-तैयारी प्लेटफ़ॉर्म है — कार्बन क्रेडिट रजिस्ट्री या कानूनी प्रमाणन संस्था नहीं। हम प्रमाण संरचित करते हैं ताकि समीक्षा तेज़ हो।",
    "India data privacy": "भारत डेटा गोपनीयता",
    "Export, erasure, consent ledger, and grievance workflows built into settings.": "सेटिंग्स में निर्यात, मिटाना, सहमति लेजर और शिकायत वर्कफ़्लो।",
    "Corporate disclosure": "कॉर्पोरेट प्रकटीकरण",
    "Principle 6 environment indicators mapped to plantation and carbon evidence.": "सिद्धांत 6 पर्यावरण संकेतक रोपण और कार्बन प्रमाण से मैप।",
    "Project GHG reports": "परियोजना GHG रिपोर्ट",
    "Structured project reports aligned with ISO 14064-2 methodology sections.": "ISO 14064-2 पद्धति अनुभागों के अनुरूप संरचित परियोजना रिपोर्ट।",
    "Nature disclosures": "प्रकृति प्रकटीकरण",
    "LEAP-style nature reports from bioacoustic richness and NDVI habitat signals.": "जैव ध्वनि समृद्धि और NDVI आवास संकेतों से LEAP-शैली प्रकृति रिपोर्ट।",
    "Verra ARR prep": "Verra ARR तैयारी",
    "Stratified sampling, buffer math, uncertainty tiers, and ICVCM alignment checklists.": "स्तरीकृत नमूनाकरण, बफर गणना, अनिश्चितता स्तर और ICVCM संरेखण चेकलिस्ट।",
    "Gold Standard LUF": "Gold Standard LUF",
    "Land Use & Forests carbon and co-benefit evidence packs for voluntary verification prep.": "Land Use & Forests कार्बन और सह-लाभ प्रमाण पैक स्वैच्छिक सत्यापन तैयारी के लिए।",
    "REDD+ MRV": "REDD+ MRV",
    "Baseline, permanence, and leakage evidence structures aligned to UNFCCC Warsaw Framework.": "UNFCCC Warsaw Framework के अनुरूप आधार रेखा, स्थायित्व और रिसाव प्रमाण संरचना।",
    "Paris Agreement traceability": "पेरिस समझौता ट्रेसेबिलिटी",
    "Geo-tagged planting ledger supporting national commitments and Article 6 transparency.": "राष्ट्रीय प्रतिबद्धताओं और अनुच्छेद 6 पारदर्शिता के लिए जियो-टैग रोपण लेजर।",
    "MoEFCC Green Credit": "MoEFCC Green Credit",
    "Land bank registration and verifier-ready planting evidence under Green Credit Rules 2023.": "Green Credit Rules 2023 के तहत भूमि बैंक पंजीकरण और सत्यापनकर्ता-तैयार रोपण प्रमाण।",
    "Core Carbon Principles": "Core Carbon Principles",
    "Integrity checklist mapped to field evidence and monitoring automation.": "फील्ड प्रमाण और निगरानी स्वचालन से मैप अखंडता चेकलिस्ट।",
    "Science-based estimates": "विज्ञान-आधारित अनुमान",
    "Biomass and CO₂e estimates with IPCC-aligned defaults and NPRT buffers.": "IPCC-संरेखित डिफ़ॉल्ट और NPRT बफर के साथ बायोमास और CO₂e अनुमान।",
    "Public planting schemes": "सार्वजनिक रोपण योजनाएँ",
    "Geo-tagged proof for highways, urban forestry, and departmental green audits.": "राजमार्ग, शहरी वनीकरण और विभागीय हरित ऑडिट के लिए जियो-टैग प्रमाण।",
    "Compensatory afforestation": "प्रतिपूरक वनीकरण",
    "Timestamped evidence packs for court-ordered and CAMPA monitoring workflows.": "न्यायालय-आदेशित और CAMPA निगरानी वर्कफ़्लो के लिए टाइमस्टैम्प प्रमाण पैक।",
    "Tamper-evident logs": "छेड़छाड़-प्रूफ लॉग",
    "Signed evidence bundles and Ed25519 verification for audit trail integrity.": "ऑडिट ट्रेल अखंडता के लिए हस्ताक्षरित प्रमाण बंडल और Ed25519 सत्यापन।",
    "Inclusive by design": "डिज़ाइन से समावेशी",
    "Hindi plus seven Indian languages on web; WCAG-tested core routes.": "वेब पर हिंदी और सात भारतीय भाषाएँ; WCAG-परीक्षित मुख्य रूट।",
    "Citizen stewardship": "नागरिक संरक्षण",
    "Bring Your Own Tree — public registration with complimentary AI health scans.": "Bring Your Own Tree — मुफ़्त AI स्वास्थ्य स्कैन के साथ सार्वजनिक पंजीकरण।",
    "Reports & exports": "रिपोर्ट और निर्यात",
    "Two evidence streams. One plantation record.": "दो प्रमाण धाराएँ। एक रोपण रिकॉर्ड।",
    "Nature and climate intelligence are reported separately — bioacoustic biodiversity on one side, GHG and methane signals with tree carbon absorption and site boundaries on the other — all generated from the same geo-tagged planting evidence.": "प्रकृति और जलवायु बुद्धिमत्ता अलग-अलग रिपोर्ट की जाती है — एक ओर जैव ध्वनि विविधता, दूसरी ओर GHG और मीथेन संकेत, पेड़ कार्बन अवशोषण और साइट सीमाएँ — सब एक ही जियो-टैग रोपण प्रमाण से।",
    "View all compliance framework exports": "सभी अनुपालन फ्रेमवर्क निर्यात देखें",
    "Bioacoustic & biodiversity": "जैव ध्वनि और जैव विविधता",
    "Soundscape monitoring, species richness, and nature disclosures from BirdNET and habitat layers at your planted sites.": "आपके रोपण स्थलों पर BirdNET और आवास परतों से ध्वनि-दृश्य निगरानी, प्रजाति समृद्धि और प्रकृति प्रकटीकरण।",
    "Biodiversity soundscape report": "जैव विविधता ध्वनि-दृश्य रिपोर्ट",
    "BirdNET species detections, acoustic richness scores, and seasonal trends for a fenced plantation site.": "बाड़बंद रोपण स्थल के लिए BirdNET प्रजाति पहचान, ध्वनिक समृद्धि स्कोर और मौसमी रुझान।",
    "TNFD LEAP nature disclosure": "TNFD LEAP प्रकृति प्रकटीकरण",
    "Locate–Evaluate–Assess–Prepare narrative weaving bioacoustic richness with NDVI habitat signals.": "जैव ध्वनि समृद्धि को NDVI आवास संकेतों के साथ जोड़ती Locate–Evaluate–Assess–Prepare कथा।",
    "Multi-taxa acoustic digest": "बहु-जाति ध्वनिक डाइजेस्ट",
    "Week-over-week soundscape health, key species presence, and alert-linked field verification notes.": "सप्ताह-दर-सप्ताह ध्वनि-दृश्य स्वास्थ्य, प्रमुख प्रजाति उपस्थिति और अलर्ट-लिंक फील्ड सत्यापन नोट्स।",
    "GHG, methane & carbon at planted sites": "रोपण स्थलों पर GHG, मीथेन और कार्बन",
    "Atmospheric methane and land-sector GHG context, modelled tree absorption, and geofenced site area identification for every planting boundary.": "वायुमंडलीय मीथेन और भू-क्षेत्र GHG संदर्भ, मॉडल पेड़ अवशोषण, और प्रत्येक रोपण सीमा के लिए जियोफेंस साइट क्षेत्र पहचान।",
    "Site methane & atmospheric GHG": "साइट मीथेन और वायुमंडलीय GHG",
    "TROPOMI-fused CH₄ and regional GHG context overlaid on plantation fences — not a credit issuance.": "रोपण बाड़ों पर TROPOMI-फ्यूज़ CH₄ और क्षेत्रीय GHG संदर्भ — क्रेडिट जारी नहीं।",
    "Tree absorption & carbon stock": "पेड़ अवशोषण और कार्बन स्टॉक",
    "Modelled biomass and CO₂e removals by species and plot with IPCC-aligned defaults and uncertainty bands.": "IPCC-संरेखित डिफ़ॉल्ट और अनिश्चितता बैंड के साथ प्रजाति और प्लॉट द्वारा मॉडल बायोमास और CO₂e निष्कासन।",
    "Plantation site boundary & area": "रोपण साइट सीमा और क्षेत्र",
    "Geofenced planting area, hectare totals, fence validation, and WGS84 coordinates for auditors and buyers.": "ऑडिटर और खरीदारों के लिए जियोफेंस रोपण क्षेत्र, हेक्टेयर कुल, बाड़ सत्यापन और WGS84 निर्देशांक।",
    "Geo-tagged tree inventory": "जियो-टैग पेड़ इन्वेंटरी",
    "Species, survival, chainage, and geotag completeness — the field baseline for carbon and compliance exports.": "प्रजाति, अवशेष, चेनेज और जियोटैग पूर्णता — कार्बन और अनुपालन निर्यात के लिए फील्ड आधार रेखा।",
    "Land-sector removals and emissions structured for corporate GHG Protocol and ISO 14064-2 project reporting.": "कॉर्पोरेट GHG Protocol और ISO 14064-2 परियोजना रिपोर्टिंग के लिए संरचित भू-क्षेत्र निष्कासन और उत्सर्जन।",
    "Standardized species occurrence archive for biodiversity partners, TNFD reviewers, and scientific reuse.": "जैव विविधता партнёров, TNFD समीक्षकों और वैज्ञानिक पुन: उपयोग के लिए मानकीकृत प्रजाति occurrence संग्रह।",
    "BRSR assurance pack": "BRSR आश्वासन पैक",
    "SEBI-aligned Principle 6 export with plantation KPIs and evidence references.": "रोपण KPI और प्रमाण संदर्भ के साथ SEBI-संरेखित सिद्धांत 6 निर्यात।",
    "ISO 14064-2 project report": "ISO 14064-2 परियोजना रिपोर्ट",
    "Project boundary, monitoring plan, and quantification sections pre-structured.": "परियोजना सीमा, निगरानी योजना और मात्रा अनुभाग पूर्व-संरचित।",
    "TNFD LEAP disclosure": "TNFD LEAP प्रकटीकरण",
    "Locate–Evaluate–Assess–Prepare narrative from satellite and bioacoustic layers.": "उपग्रह और जैव ध्वनि परतों से Locate–Evaluate–Assess–Prepare कथा।",
    "GHG land-sector inventory": "GHG भू-क्षेत्र इन्वेंटरी",
    "Land-sector removals and emissions structured for corporate GHG Protocol reporting.": "कॉर्पोरेट GHG Protocol रिपोर्टिंग के लिए संरचित भू-क्षेत्र निष्कासन और उत्सर्जन।",
    "Darwin Core occurrence pack": "Darwin Core occurrence पैक",
    "Species occurrence archive for biodiversity partners and scientific reuse.": "जैव विविधता партнёров और वैज्ञानिक पुन: उपयोग के लिए प्रजाति occurrence संग्रह।",
    "Carbon credit ledger": "कार्बन क्रेडिट लेजर",
    "Serial tracking, verifier sampling, and NPRT buffer assessments per project.": "प्रति परियोजना सीरियल ट्रैकिंग, सत्यापनकर्ता नमूनाकरण और NPRT बफर मूल्यांकन।",
    "Gold Standard LUF report": "Gold Standard LUF रिपोर्ट",
    "Land Use & Forests framework-mapped PDF and Excel for voluntary verification prep.": "स्वैच्छिक सत्यापन तैयारी के लिए Land Use & Forests फ्रेमवर्क-मैप PDF और Excel।",
    "REDD+ MRV report": "REDD+ MRV रिपोर्ट",
    "Baseline, permanence, and leakage sections structured for REDD+ program review.": "REDD+ कार्यक्रम समीक्षा के लिए संरचित आधार रेखा, स्थायित्व और रिसाव अनुभाग।",
    "NDC-aligned planting ledger export with Article 6 cooperative-approaches context.": "अनुच्छेद 6 सहकारी दृष्टिकोण संदर्भ के साथ NDC-संरेखित रोपण लेजर निर्यात।",
    "Green Credit India pack": "Green Credit India पैक",
    "MoEFCC Green Credit Programme evidence with land bank and survival KPIs.": "भूमि बैंक और अवशेष KPI के साथ MoEFCC Green Credit Programme प्रमाण।",
    "Tree inventory": "पेड़ इन्वेंटरी",
    "Species, survival, geotag status, and chainage for compliance packs.": "अनुपालन पैक के लिए प्रजाति, अवशेष, जियोटैग स्थिति और चेनेज।",
    "Carbon stock estimate": "कार्बन स्टॉक अनुमान",
    "Modelled biomass and CO₂e with IPCC-aligned defaults — not a credit issuance.": "IPCC-संरेखित डिफ़ॉल्ट के साथ मॉडल बायोमास और CO₂e — क्रेडिट जारी नहीं।",
    "Biodiversity soundscape": "जैव विविधता ध्वनि-दृश्य",
    "BirdNET richness and habitat signals for a fenced plantation site.": "बाड़बंद रोपण स्थल के लिए BirdNET समृद्धि और आवास संकेत।",
    "ESG stakeholder summary": "ESG हितधारक सारांश",
    "Combined carbon, biodiversity, and NDVI narrative for boards and buyers.": "बोर्ड और खरीदारों के लिए संयुक्त कार्बन, जैव विविधता और NDVI कथा।",
    "Portfolio health digest": "पोर्टफोलियो स्वास्थ्य डाइजेस्ट",
    "NDVI trends, SAR threats, and compliance completion scores for leadership.": "नेतृत्व के लिए NDVI रुझान, SAR खतरे और अनुपालन पूर्णता स्कोर।",
    "Signed evidence bundle": "हस्ताक्षरित प्रमाण बंडल",
    "Tamper-evident ZIP with Ed25519 audit-chain verification for third-party review.": "तीसरे पक्ष समीक्षा के लिए Ed25519 ऑडिट-श्रृंखला सत्यापन वाला छेड़छाड़-प्रूफ ZIP।",
    "Planting programs": "रोपण कार्यक्रम",
    "One workspace. Every compliance pathway.": "एक कार्यक्षेत्र। हर अनुपालन मार्ग।",
    "Enroll in BYOT, government, corporate ESG, or NGO programs from a single account. Each pathway applies the right validation rules without fragmenting your data.": "एक खाते से BYOT, सरकार, कॉर्पोरेट ESG या NGO कार्यक्रमों में नामांकन। प्रत्येक मार्ग सही सत्यापन नियम लागू करता है — डेटा विखंडित किए बिना।",
    "BYOT Public": "BYOT सार्वजनिक",
    "Citizens and schools tag trees in minutes with mobile-first registration and QR passports.": "नागरिक और स्कूल मिनटों में मोबाइल-प्रथम पंजीकरण और QR पासपोर्ट से पेड़ टैग करते हैं।",
    "Most popular": "सबसे लोकप्रिय",
    "Government & Public Sector": "सरकार और सार्वजनिक क्षेत्र",
    "NHAI chainage, CAMPA monitoring, Nagar Van urban templates, and audit-grade field evidence.": "NHAI चेनेज, CAMPA निगरानी, नगर वन शहरी टेम्पलेट और ऑडिट-ग्रेड फील्ड प्रमाण।",
    "Govt ready": "सरकारी तैयार",
    "Industry & Corporate ESG": "उद्योग और कॉर्पोरेट ESG",
    "Plantation baselines, BRSR exports, supplier traceability, and board-ready sustainability packs.": "रोपण आधार रेखा, BRSR निर्यात, आपूर्तिकर्ता ट्रेसेबिलिटी और बोर्ड-तैयार स्थिरता पैक।",
    "ESG": "ESG",
    "NGO & Community": "NGO और समुदाय",
    "Watershed restoration, farmer groups, and community nurseries with shared dashboards.": "जलग्रहीय बहाली, किसान समूह और साझा डैशबोर्ड वाली सामुदायिक नर्सरी।",
    "Community": "समुदाय",
    "From first tree to audit-ready portfolio": "पहले पेड़ से ऑडिट-तैयार पोर्टफोलियो तक",
    "A guided flow for field teams, backed by automated monitoring and executive reporting.": "फील्ड टीमों के लिए मार्गदर्शित फ्लो — स्वचालित निगरानी और कार्यकारी रिपोर्टिंग के साथ।",
    "Create your workspace": "अपना कार्यक्षेत्र बनाएँ",
    "Enroll & set up": "नामांकन और सेटअप",
    "Pick your program — BYOT, government, ESG, or NGO — and complete the project setup wizard with scheme-specific rules.": "अपना कार्यक्रम चुनें — BYOT, सरकार, ESG या NGO — और योजना-विशिष्ट नियमों के साथ प्रोजेक्ट सेटअप विज़ार्ड पूरा करें।",
    "Register evidence": "प्रमाण पंजीकृत करें",
    "Capture trees with GPS, photos, and species on web or mobile. Chainage auto-advances for highway corridors.": "वेब या मोबाइल पर GPS, फ़ोटो और प्रजाति के साथ पेड़ कैप्चर करें। राजमार्ग गलियारों के लिए चेनेज स्वतः आगे बढ़ता है।",
    "Monitor continuously": "निरंतर निगरानी",
    "Satellite NDVI, SAR integrity, bioacoustic richness, and AI health scoring watch your sites around the clock.": "उपग्रह NDVI, SAR अखंडता, जैव ध्वनि समृद्धि और AI स्वास्थ्य स्कोरिंग चौबीसों घंटे आपकी साइटों की देखभाल करते हैं।",
    "Act on alerts": "अलर्ट पर कार्रवाई",
    "Supervisors receive canopy stress and anomaly alerts with field verification workflows built in.": "पर्यवेक्षकों को वनस्पति तनाव और विसंगति अलर्ट मिलते हैं — फील्ड सत्यापन वर्कफ़्लो के साथ।",
    "Report with confidence": "विश्वास के साथ रिपोर्ट",
    "Export BRSR, ISO, TNFD, VM0047, Gold Standard, REDD+, Paris/NDC, and Green Credit packs — plus signed evidence bundles for auditor review.": "BRSR, ISO, TNFD, VM0047, Gold Standard, REDD+, Paris/NDC और Green Credit पैक निर्यात — ऑडिटर समीक्षा के लिए हस्ताक्षरित प्रमाण बंडल सहित।",
    "Platform preview": "प्लेटफ़ॉर्म पूर्वावलोकन",
    "Live command center": "लाइव कमांड सेंटर",
    "See your plantation portfolio at a glance": "अपना रोपण पोर्टफोलियो एक नज़र में देखें",
    "Executive dashboards surface tree health, SAR anomalies, species richness, compliance completion, and alert queues — with exports tailored to enrolled programs.": "कार्यकारी डैशबोर्ड पेड़ स्वास्थ्य, SAR विसंगतियाँ, प्रजाति समृद्धि, अनुपालन पूर्णता और अलर्ट कतार दिखाते हैं — नामांकित कार्यक्रमों के अनुरूप निर्यात।",
    "Interactive maps with NDVI and SAR integrity overlays": "NDVI और SAR अखंडता ओवरले वाले इंटरैक्टिव मानचित्र",
    "Executive dashboard for health, biodiversity, and compliance KPIs": "स्वास्थ्य, जैव विविधता और अनुपालन KPI के लिए कार्यकारी डैशबोर्ड",
    "Multi-program enrollment on a single organization account": "एक संगठन खाते पर बहु-कार्यक्रम नामांकन",
    "REST API, webhooks, and GIS-friendly exports": "REST API, webhooks और GIS-अनुकूल निर्यात",
    "Trees registered": "पंजीकृत पेड़",
    "Mean NDVI": "औसत NDVI",
    "Passport complete": "पासपोर्ट पूर्ण",
    "SAR canopy integrity": "SAR वनस्पति अखंडता",
    "2 sites flagged": "2 साइट चिह्नित",
    "Bioacoustic richness": "जैव ध्वनि समृद्धि",
    "Stable this week": "इस सप्ताह स्थिर",
    "Compliance checklists": "अनुपालन चेकलिस्ट",
    "87% complete": "87% पूर्ण",
    "CO₂e estimate": "CO₂e अनुमान",
    "1,240 tCO₂e (modelled)": "1,240 tCO₂e (मॉडल)",
    "Call to action": "कार्रवाई आह्वान",
    "Ready to begin?": "शुरू करने के लिए तैयार?",
    "Turn every tree into audit-ready environmental evidence": "हर पेड़ को ऑडिट-तैयार पर्यावरण प्रमाण में बदलें",
    "Join organizations using Aranyix for plantation monitoring, biodiversity assessment, and compliance exports — from citizen BYOT to government-grade field programs.": "रोपण निगरानी, जैव विविधता मूल्यांकन और अनुपालन निर्यात के लिए Aranyix उपयोग करने वाले संगठनों से जुड़ें — नागरिक BYOT से सरकारी-स्तर फील्ड कार्यक्रम तक।",
    "Get started free": "मुफ़्त में शुरू करें",
    "Sign in to workspace": "कार्यक्षेत्र में साइन इन",
    "Learn more": "और जानें",
    # Nav — biodiversity / carbon anchors
    "Biodiversity": "जैव विविधता",
    "Carbon": "कार्बन",
    # Biodiversity intelligence section
    "Biodiversity Intelligence": "जैव विविधता बुद्धिमत्ता",
    "Listen to the landscape": "परिदृश्य को सुनें",
    "Turn field sound into biodiversity evidence.": "फील्ड ध्वनि को जैव विविधता प्रमाण में बदलें।",
    "Open bioacoustic workspace": "जैव ध्वनि कार्यक्षेत्र खोलें",
    "Field recording": "फील्ड रिकॉर्डिंग",
    "Bioacoustic engine": "जैव ध्वनि इंजन",
    "Species model": "प्रजाति मॉडल",
    "Verified evidence": "सत्यापित प्रमाण",
    # GHG / carbon intelligence section
    "Project Carbon Intelligence": "परियोजना कार्बन बुद्धिमत्ता",
    "Project GHG emissions within your boundary": "आपकी सीमा के भीतर परियोजना GHG उत्सर्जन",
    "Spatial greenhouse-gas intelligence for planted sites — satellite methane context, registered sources, dispersion modelling, and fusion inside the project work area.": "रोपण स्थलों के लिए स्थानिक ग्रीनहाउस गैस बुद्धिमत्ता — उपग्रह मीथेन संदर्भ, पंजीकृत स्रोत, प्रसरण मॉडलिंग, और परियोजना कार्य क्षेत्र के भीतर फ्यूजन।",
    "Open emissions workspace": "उत्सर्जन कार्यक्षेत्र खोलें",
    # Reports hub (v3 catalog)
    "Sixteen live exports. One evidence graph.": "सोलह लाइव निर्यात। एक प्रमाण ग्राफ।",
    "Framework-mapped assurance packs generated from the same plantation record — carbon, biodiversity, disclosure, and compliance exports for auditors, program officers, and ESG teams. Assurance packs, not credit issuance.": "एक ही रोपण रिकॉर्ड से फ्रेमवर्क-मैप आश्वासन पैक — कार्बन, जैव विविधता, प्रकटीकरण और अनुपालन निर्यात ऑडिटर, कार्यक्रम अधिकारी और ESG टीमों के लिए। आश्वासन पैक, क्रेडिट जारी नहीं।",
    "Open full reports workspace": "पूर्ण रिपोर्ट कार्यक्षेत्र खोलें",
    "Carbon stock & tree absorption": "कार्बन स्टॉक और पेड़ अवशोषण",
    "Modelled biomass and CO₂e removals by species and plot with IPCC-aligned defaults.": "IPCC-संरेखित डिफ़ॉल्ट के साथ प्रजाति और प्लॉट द्वारा मॉडल बायोमास और CO₂e निष्कासन।",
    "TROPOMI-fused CH₄ context overlaid on project work areas with dispersion and fusion review.": "प्रसरण और फ्यूजन समीक्षा के साथ परियोजना कार्य क्षेत्रों पर TROPOMI-फ्यूज़ CH₄ संदर्भ।",
    "Satellite + source fusion": "उपग्रह + स्रोत फ्यूजन",
    "Organizational GHG inventory": "संगठनात्मक GHG इन्वेंटरी",
    "Org-level inventory export complementing ISO 14064-2 project quantification reports.": "ISO 14064-2 परियोजना मात्रा रिपोर्टों को पूरक संगठन-स्तर इन्वेंटरी निर्यात।",
    "BirdNET species detections, acoustic richness scores, and seasonal trends for a fenced site.": "बाड़बंद स्थल के लिए BirdNET प्रजाति पहचान, ध्वनिक समृद्धि स्कोर और मौसमी रुझान।",
    "Standardized species occurrence archive for biodiversity partners and scientific reuse.": "जैव विविधता партнёров और वैज्ञानिक पुन: उपयोग के लिए मानकीकृत प्रजाति occurrence संग्रह।",
    "Biodiversity evidence summary": "जैव विविधता प्रमाण सारांश",
    "Species richness, habitat signals, and acoustic health for a plantation fence boundary.": "रोपण बाड़ सीमा के लिए प्रजाति समृद्धि, आवास संकेत और ध्वनिक स्वास्थ्य।",
    "ESG nature narrative": "ESG प्रकृति कथा",
    "Combined biodiversity, NDVI habitat, and acoustic richness narrative for stakeholders.": "हितधारकों के लिए संयुक्त जैव विविधता, NDVI आवास और ध्वनिक समृद्धि कथा।",
    "Org + project roll-up": "संगठन + परियोजना रोल-अप",
    "Per plantation site": "प्रति रोपण स्थल",
    "National inventory handoff": "राष्ट्रीय इन्वेंटरी हैंडऑफ",
    "Org-level IPCC activity tables with leakage, buffer, and SAR integrity flags for ETF/BTR pilots.": "ETF/BTR पायलट के लिए रिसाव, बफर और SAR अखंडता फ्लैग के साथ संगठन-स्तर IPCC गतिविधि तालिकाएँ।",
    "FLAG land-sector worksheet": "FLAG भू-क्षेत्र वर्कशीट",
    "Land-related removals vs target boundary linked to VM0047 and GHG exports.": "VM0047 और GHG निर्यात से जुड़े लक्ष्य सीमा के विरुद्ध भू-संबंधित निष्कासन।",
    "Supplier geo due diligence": "आपूर्तिकर्ता जियो due diligence",
    "WGS84 coordinate pack with BRSR value-chain linkage for corporate buyers.": "कॉर्पोरेट खरीदारों के लिए BRSR मूल्य-श्रृंखला लिंकेज के साथ WGS84 निर्देशांक पैक।",
    "Geo-tagged tree inventory": "जियो-टैग पेड़ इन्वेंटरी",
    "Species, survival, chainage, and geotag completeness for compliance packs.": "अनुपालन पैक के लिए प्रजाति, अवशेष, चेनेज और जियोटैग पूर्णता।",
    "Article 6 readiness": "अनुच्छेद 6 तैयारी",
    "Cooperative approaches checklist with corresponding adjustment refs and serial traceability.": "समकक्ष समायोजन संदर्भ और सीरियल ट्रेसेबिलिटी के साथ सहकारी दृष्टिकोण चेकलिस्ट।",
    "ESF safeguard screening": "ESF सुरक्षा स्क्रीनिंग",
    "PS5 land/tenure and PS6 biodiversity evidence packs for DFI-backed corridors.": "DFI-समर्थित गलियारों के लिए PS5 भूमि/अधिकार और PS6 जैव विविधता प्रमाण पैक।",
    "UNDP SES screening": "UNDP SES स्क्रीनिंग",
    "Social and environmental risk screening with stakeholder engagement exports.": "हितधारक सहभागिता निर्यात के साथ सामाजिक और पर्यावरण जोखिम स्क्रीनिंग।",
    "Land-sector targets": "भू-क्षेत्र लक्ष्य",
    "FLAG removals worksheet linked to VM0047 and GHG Protocol single source of truth.": "VM0047 और GHG Protocol एकल सत्य स्रोत से जुड़ा FLAG निष्कासन वर्कशीट।",
    "Global Biodiversity Framework": "वैश्विक जैव विविधता ढांचा",
    "Targets 2 & 3 indicator mapping bridged to TNFD LEAP disclosures.": "लक्ष्य 2 और 3 संकेतक मैपिंग TNFD LEAP प्रकटीकरण से जुड़ी।",
    "Supplier geo MRV": "आपूर्तिकर्ता जियो MRV",
    "Geo-coordinate due diligence for corporate buyers and BRSR value-chain linkage.": "कॉर्पोरेट खरीदारों और BRSR मूल्य-श्रृंखला लिंकेज के लिए जियो-निर्देशांक due diligence।",
}


def translate_value(val):
    if isinstance(val, str):
        return T.get(val, val)
    if isinstance(val, list):
        return [translate_value(v) for v in val]
    if isinstance(val, dict):
        return {k: translate_value(v) for k, v in val.items()}
    return val


def main():
    data = json.loads(SRC.read_text(encoding="utf-8"))
    hi = translate_value(data)
    DST.write_text(json.dumps(hi, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    untranslated = []

    def collect_untranslated(en, hi_obj, path=""):
        if isinstance(en, str) and isinstance(hi_obj, str) and en == hi_obj and en.strip() and not en.startswith("http") and en not in ("DPDP Act", "BRSR / SEBI", "ISO 14064-2", "TNFD", "VM0047", "Gold Standard", "REDD+", "Paris / NDC", "Green Credit", "ICVCM", "IPCC AR6", "NHAI / Govt", "CAMPA / NGT", "Audit chain", "WCAG + i18n", "BYOT", "SAR + NDVI", "DPDP ready", "PWA", "24/7", "10M+", "100%", "15+", "8", "SAR + NDVI", "PDF · XLSX", "ZIP · JSON", "PDF", "ZIP", "01", "02", "03", "04", "05", "12,480", "0.72", "94%", "2 sites flagged", "87% complete", "1,240 tCO₂e (modelled)", "Stable this week", "Inventory", "Carbon", "Biodiversity", "Evidence", "Executive", "GHG Protocol", "Darwin Core", "ISO 14064-2", "BRSR", "Gold Standard", "REDD+", "Paris / NDC", "Green Credit", "ESG", "Aranyix"):
            if any(c.isalpha() for c in en) and len(en) > 3:
                untranslated.append(f"{path}: {en[:80]}")

    collect_untranslated(data, hi)
    print(f"Wrote {DST}")
    if untranslated:
        print(f"Note: {len(untranslated)} strings kept in English (codes/brands/numbers)")


if __name__ == "__main__":
    main()
