"""Tree digital passport: QR code PNG + PDF document."""

from __future__ import annotations

import io
from typing import Any

import qrcode
from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.units import mm
from reportlab.platypus import (
    Image,
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)

BRAND_GREEN = colors.HexColor("#15803D")
BRAND_LIGHT = colors.HexColor("#DCFCE7")


def generate_qr_png(payload: str, box_size: int = 8) -> bytes:
    qr = qrcode.QRCode(
        version=None,
        error_correction=qrcode.constants.ERROR_CORRECT_M,
        box_size=box_size,
        border=2,
    )
    qr.add_data(payload)
    qr.make(fit=True)
    img = qr.make_image(fill_color="#0f5132", back_color="white")
    buf = io.BytesIO()
    img.save(buf, format="PNG")
    return buf.getvalue()


def generate_passport_pdf(passport: dict[str, Any]) -> bytes:
    buf = io.BytesIO()
    doc = SimpleDocTemplate(
        buf,
        pagesize=A4,
        leftMargin=18 * mm,
        rightMargin=18 * mm,
        topMargin=18 * mm,
        bottomMargin=18 * mm,
        title=f"BYOT Tree Passport {passport.get('public_code')}",
        author="BYOT",
    )
    styles = getSampleStyleSheet()
    h1 = styles["Heading1"]
    h1.textColor = BRAND_GREEN
    body = styles["BodyText"]

    story: list = []
    story.append(Paragraph("BYOT — Tree Digital Passport", h1))
    story.append(Spacer(1, 4 * mm))
    story.append(
        Paragraph(
            "<b>Bring Your Own Tree</b> · Verifiable, AI- and satellite-monitored "
            "carbon evidence for every registered tree.",
            body,
        )
    )
    story.append(Spacer(1, 6 * mm))

    qr_png = generate_qr_png(
        passport.get("qr_url") or passport.get("public_code", ""), box_size=6
    )
    qr_img = Image(io.BytesIO(qr_png), width=45 * mm, height=45 * mm)

    data = [
        ["Public Code", passport.get("public_code", "—"), qr_img],
        ["Species", passport.get("species", "Unknown"), ""],
        [
            "Location",
            f"{passport.get('latitude', 0):.5f}, {passport.get('longitude', 0):.5f}",
            "",
        ],
        ["Planted", str(passport.get("planted_at") or "—"), ""],
        ["Health", passport.get("health", "unknown").title(), ""],
        ["Carbon Stored", f"{passport.get('carbon_kg', 0):.2f} kg", ""],
        [
            "Satellite Verified",
            "✓ Yes" if passport.get("satellite_verified") else "Pending",
            "",
        ],
    ]
    table = Table(data, colWidths=[45 * mm, 75 * mm, 50 * mm])
    table.setStyle(
        TableStyle(
            [
                ("FONTNAME", (0, 0), (-1, -1), "Helvetica"),
                ("FONTSIZE", (0, 0), (-1, -1), 11),
                ("TEXTCOLOR", (0, 0), (0, -1), BRAND_GREEN),
                ("BACKGROUND", (0, 0), (0, -1), BRAND_LIGHT),
                ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
                ("SPAN", (2, 0), (2, 6)),
                ("ALIGN", (2, 0), (2, 0), "CENTER"),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
                ("TOPPADDING", (0, 0), (-1, -1), 6),
                ("LINEBELOW", (0, 0), (1, -1), 0.25, colors.grey),
            ]
        )
    )
    story.append(table)
    story.append(Spacer(1, 10 * mm))
    story.append(
        Paragraph(
            "This passport is generated by the BYOT platform. AI species and "
            "health classifications, satellite NDVI evidence, and carbon "
            "estimates are versioned and reproducible. Verify online at "
            f"<font color='#15803D'>{passport.get('qr_url', '')}</font>.",
            body,
        )
    )
    doc.build(story)
    return buf.getvalue()
