"""Scheme-specific metadata field definitions (govt reference IDs)."""

from __future__ import annotations

from typing import Any

# Reuse planting program form field shape for API/UI parity.
FormField = dict[str, Any]

_COMMON_APO_FIELDS: list[FormField] = [
    {
        "key": "apo_financial_year",
        "label": "APO financial year",
        "type": "text",
        "required": True,
        "placeholder": "2025-26",
        "help_text": "State CAMPA Annual Plan of Operation financial year.",
    },
    {
        "key": "state_name",
        "label": "State / UT",
        "type": "text",
        "required": True,
        "placeholder": "Rajasthan",
    },
]

SCHEME_METADATA_FIELDS: dict[str, list[FormField]] = {
    "campa_ca": [
        {
            "key": "pca_number",
            "label": "PCA / CA proposal number",
            "type": "text",
            "required": True,
            "placeholder": "PCA/RAJ/2025/1842",
            "help_text": "Compensatory afforestation proposal reference under FC Act.",
        },
        {
            "key": "forest_diversion_id",
            "label": "Forest diversion / FC reference",
            "type": "text",
            "required": True,
            "placeholder": "FC-8821-2024",
            "help_text": "Forest Conservation Act diversion approval ID.",
        },
        {
            "key": "state_campa_account",
            "label": "State CAMPA account",
            "type": "text",
            "required": False,
            "placeholder": "Rajasthan State CAMPA",
        },
        *_COMMON_APO_FIELDS,
        {
            "key": "ca_land_parcel_id",
            "label": "CA land parcel / block ID",
            "type": "text",
            "required": False,
            "help_text": "GIS or forest department parcel identifier for CA land.",
        },
        {
            "key": "ngt_case_number",
            "label": "NGT case number (if applicable)",
            "type": "text",
            "required": False,
        },
        {
            "key": "ngt_order_ref",
            "label": "NGT order reference",
            "type": "text",
            "required": False,
            "help_text": "Court order or monitoring direction reference for CA compliance.",
        },
    ],
    "gim_restoration": [
        {
            "key": "gim_sub_mission",
            "label": "GIM sub-mission",
            "type": "select",
            "required": True,
            "options": [
                {"value": "SM-1", "label": "SM-1 — Forest quality"},
                {"value": "SM-2", "label": "SM-2 — Eco restoration"},
                {"value": "SM-3", "label": "SM-3 — Urban tree cover"},
                {"value": "SM-4", "label": "SM-4 — Agro-forestry"},
            ],
        },
        {
            "key": "state_annual_plan_ref",
            "label": "State annual plan reference",
            "type": "text",
            "required": True,
        },
        *_COMMON_APO_FIELDS,
        {
            "key": "jfmc_name",
            "label": "JFMC / village committee",
            "type": "text",
            "required": False,
            "help_text": "Joint Forest Management Committee when applicable.",
        },
    ],
    "mishti_mangrove": [
        {
            "key": "mishti_project_id",
            "label": "MISHTI project ID",
            "type": "text",
            "required": True,
        },
        {
            "key": "coastal_state",
            "label": "Coastal state / UT",
            "type": "text",
            "required": True,
        },
        {
            "key": "coastal_district",
            "label": "Coastal district",
            "type": "text",
            "required": True,
        },
        {
            "key": "crz_category",
            "label": "CRZ category",
            "type": "select",
            "required": True,
            "options": [
                {"value": "CRZ-I", "label": "CRZ-I — Ecologically sensitive"},
                {"value": "CRZ-II", "label": "CRZ-II — Developed"},
                {"value": "CRZ-III", "label": "CRZ-III — Undeveloped"},
                {"value": "CRZ-IV", "label": "CRZ-IV — Water body"},
            ],
        },
        {
            "key": "restoration_area_ha",
            "label": "Restoration area (hectares)",
            "type": "number",
            "required": True,
            "min": 0.01,
        },
    ],
    "nagar_van": [
        {
            "key": "nagar_van_project_id",
            "label": "Nagar Van project ID",
            "type": "text",
            "required": True,
        },
        {
            "key": "ulb_name",
            "label": "ULB / municipal body",
            "type": "text",
            "required": True,
        },
        {
            "key": "urban_forest_name",
            "label": "Urban forest / park name",
            "type": "text",
            "required": True,
        },
        {
            "key": "target_trees",
            "label": "Scheme target trees",
            "type": "number",
            "required": False,
            "min": 1,
            "help_text": "Nagar Van Yojana typically targets 10,000+ trees per site.",
        },
    ],
    "nhai_highway": [
        {
            "key": "nhai_package_code",
            "label": "NHAI package / contract code",
            "type": "text",
            "required": True,
            "placeholder": "NH-44-PKG-3",
        },
        {
            "key": "highway_number",
            "label": "Highway number",
            "type": "text",
            "required": True,
            "placeholder": "NH-44",
        },
        {
            "key": "dpr_milestone",
            "label": "DPR / BOQ milestone",
            "type": "text",
            "required": False,
        },
        {
            "key": "chainage_start_km",
            "label": "Chainage start (km)",
            "type": "number",
            "required": False,
            "min": 0,
        },
        {
            "key": "chainage_end_km",
            "label": "Chainage end (km)",
            "type": "number",
            "required": False,
            "min": 0,
        },
    ],
    "mgnrega_convergence": [
        {
            "key": "mgnrega_work_estimate_id",
            "label": "MGNREGA work estimate ID",
            "type": "text",
            "required": True,
        },
        {
            "key": "gram_panchayat",
            "label": "Gram panchayat",
            "type": "text",
            "required": True,
        },
        {
            "key": "person_days_planned",
            "label": "Person-days planned",
            "type": "number",
            "required": True,
            "min": 1,
        },
        {
            "key": "financial_year",
            "label": "Financial year",
            "type": "text",
            "required": True,
            "placeholder": "2025-26",
        },
    ],
    "jal_shakti_riparian": [
        {
            "key": "river_name",
            "label": "River / tributary",
            "type": "text",
            "required": True,
        },
        {
            "key": "buffer_km",
            "label": "Riparian buffer (km each side)",
            "type": "number",
            "required": True,
            "min": 0.1,
            "max": 10,
        },
        {
            "key": "jal_shakti_scheme_ref",
            "label": "Jal Shakti / NMCG scheme reference",
            "type": "text",
            "required": False,
        },
    ],
    "green_credit_india": [
        {
            "key": "green_credit_land_bank_id",
            "label": "Green Credit land bank ID",
            "type": "text",
            "required": True,
            "help_text": "MoEFCC Green Credit Programme land bank registration.",
        },
        {
            "key": "gcp_activity_type",
            "label": "GCP activity type",
            "type": "select",
            "required": True,
            "options": [
                {"value": "tree_plantation", "label": "Tree plantation"},
                {"value": "eco_restoration", "label": "Eco restoration"},
            ],
        },
        {
            "key": "verifier_reference",
            "label": "Verifier / ICFRE reference",
            "type": "text",
            "required": False,
        },
    ],
    "mining_reclamation": [
        {
            "key": "mine_lease_number",
            "label": "Mine lease number",
            "type": "text",
            "required": True,
            "placeholder": "ML-08/2020/1234",
            "help_text": "IBM-registered mining lease number under MMDR.",
        },
        {
            "key": "ibm_closure_plan_ref",
            "label": "IBM progressive closure plan reference",
            "type": "text",
            "required": True,
            "placeholder": "IBM/PCP/2025/RJ/042",
            "help_text": "Approved progressive mine closure plan (PMCP) reference.",
        },
        {
            "key": "closure_plan_year",
            "label": "Closure plan year",
            "type": "number",
            "required": True,
            "min": 2000,
            "max": 2100,
            "help_text": "Year of the approved progressive closure plan.",
        },
        {
            "key": "mineral_type",
            "label": "Mineral type",
            "type": "select",
            "required": True,
            "options": [
                {"value": "iron_ore", "label": "Iron ore"},
                {"value": "limestone", "label": "Limestone"},
                {"value": "coal", "label": "Coal / lignite"},
                {"value": "bauxite", "label": "Bauxite"},
                {"value": "manganese", "label": "Manganese"},
                {"value": "other", "label": "Other mineral"},
            ],
        },
        {
            "key": "reclamation_block_type",
            "label": "Reclamation block type",
            "type": "select",
            "required": True,
            "options": [
                {"value": "overburden_dump", "label": "Overburden dump"},
                {"value": "pit_wall", "label": "Pit wall / bench"},
                {"value": "buffer_zone", "label": "Lease buffer zone"},
                {"value": "haul_road", "label": "Haul road / corridor"},
                {"value": "tailings_pond", "label": "Tailings / settling pond"},
                {"value": "green_belt_strip", "label": "Green belt strip"},
                {"value": "void_rehab", "label": "Void / pit rehabilitation"},
            ],
        },
        {
            "key": "lease_area_ha",
            "label": "Lease area (ha)",
            "type": "number",
            "required": True,
            "min": 0.1,
            "help_text": "Total mining lease area in hectares.",
        },
        {
            "key": "closure_phase",
            "label": "Progressive closure phase",
            "type": "select",
            "required": True,
            "options": [
                {"value": "phase_i_dump_stabilization", "label": "Phase I — dump stabilization"},
                {"value": "phase_ii_greenbelt", "label": "Phase II — green belt"},
                {"value": "phase_iii_ecorestoration", "label": "Phase III — eco-restoration"},
                {"value": "final_closure", "label": "Final closure"},
            ],
        },
        {
            "key": "state_mining_dept_ref",
            "label": "State mining department reference",
            "type": "text",
            "required": False,
            "help_text": "Optional state DMG / geology department file reference.",
        },
        {
            "key": "green_credit_land_bank_id",
            "label": "Green Credit land bank ID (optional)",
            "type": "text",
            "required": False,
            "help_text": "Link if this reclamation block is also registered under MoEFCC GCP.",
        },
    ],
    "sahakar_van": [
        {
            "key": "sahakar_van_project_id",
            "label": "Sahakar Van project ID",
            "type": "text",
            "required": True,
            "placeholder": "SV-NCCF-RAJ-2026-01",
            "help_text": "NCCF / Ministry of Cooperation project reference.",
        },
        {
            "key": "nccf_project_ref",
            "label": "NCCF project reference",
            "type": "text",
            "required": True,
            "placeholder": "NCCF/SV/2026/SUMEL",
        },
        {
            "key": "amul_union_name",
            "label": "Amul dairy union / federation",
            "type": "text",
            "required": True,
            "placeholder": "Amul — Gujarat Cooperative Milk Marketing Federation",
        },
        {
            "key": "cooperative_society_name",
            "label": "Primary cooperative society",
            "type": "text",
            "required": True,
            "help_text": "Implementing cooperative society or women's group.",
        },
        {
            "key": "village_name",
            "label": "Village / site name",
            "type": "text",
            "required": True,
            "placeholder": "Sumel",
        },
        {
            "key": "district",
            "label": "District",
            "type": "text",
            "required": True,
            "placeholder": "Jaipur",
        },
        {
            "key": "state_name",
            "label": "State / UT",
            "type": "text",
            "required": True,
            "placeholder": "Rajasthan",
        },
        {
            "key": "site_area_acres",
            "label": "Site area (acres)",
            "type": "number",
            "required": True,
            "min": 1,
            "help_text": "Pilot sites are typically 10–64 acres of arid or degraded land.",
        },
        {
            "key": "plantation_method",
            "label": "Plantation method",
            "type": "select",
            "required": True,
            "options": [
                {"value": "mixed", "label": "Mixed — Miyawaki + conventional"},
                {"value": "miyawaki", "label": "Miyawaki dense forest"},
                {"value": "conventional", "label": "Conventional row planting"},
            ],
        },
        {
            "key": "local_partner_agency",
            "label": "Local partner agency (optional)",
            "type": "text",
            "required": False,
            "help_text": "e.g. Jaipur Development Authority, district forest office.",
        },
        {
            "key": "target_trees",
            "label": "Target trees",
            "type": "number",
            "required": False,
            "min": 1,
            "help_text": "Total saplings planned for the cooperative forest site.",
        },
    ],
    "dfi_green_corridor": [
        *_COMMON_APO_FIELDS,
        {
            "key": "dfi_lender_ref",
            "label": "DFI / lender reference",
            "type": "text",
            "required": True,
            "placeholder": "WB-IND-GREEN-2025-001",
            "help_text": "World Bank, ADB, or bilateral DFI project reference.",
        },
        {
            "key": "dfi_project_id",
            "label": "DFI project ID",
            "type": "text",
            "required": False,
        },
        {
            "key": "nhai_package_ref",
            "label": "NHAI package / corridor ref",
            "type": "text",
            "required": False,
            "placeholder": "NH-44-PKG-3",
        },
        {
            "key": "pca_number",
            "label": "CAMPA PCA number (if converged)",
            "type": "text",
            "required": False,
        },
        {
            "key": "ngt_order_ref",
            "label": "NGT order reference",
            "type": "text",
            "required": False,
        },
    ],
    "raj_amrit_poshan_vatika": [
        {
            "key": "apv_site_id",
            "label": "Amrit Poshan Vatika site ID",
            "type": "text",
            "required": True,
            "placeholder": "APV-RJ-2026-1842",
            "help_text": "Rajasthan Forest Department or district nodal site reference.",
        },
        {
            "key": "site_type",
            "label": "Site type",
            "type": "select",
            "required": True,
            "options": [
                {"value": "anganwadi", "label": "Anganwadi centre"},
                {"value": "shg", "label": "SHG nutri-garden"},
                {"value": "panchayat", "label": "Gram panchayat land"},
                {"value": "school", "label": "School / campus"},
            ],
        },
        {
            "key": "anganwadi_name",
            "label": "Anganwadi / centre name",
            "type": "text",
            "required": False,
            "placeholder": "AWC Kishangarh Bas",
        },
        {
            "key": "shg_name",
            "label": "SHG name",
            "type": "text",
            "required": False,
            "placeholder": "Mahila Vikas SHG",
        },
        {
            "key": "gram_panchayat",
            "label": "Gram panchayat",
            "type": "text",
            "required": True,
        },
        {
            "key": "mgnrega_job_card_ref",
            "label": "MGNREGA job card / work estimate",
            "type": "text",
            "required": False,
            "help_text": "Convergence reference when plantation wages are under MGNREGA.",
        },
        {
            "key": "site_area_ha",
            "label": "Site area (hectares)",
            "type": "number",
            "required": True,
            "min": 0.1,
            "max": 0.5,
            "help_text": "Typical nutri-garden sites are 0.1–0.5 ha.",
        },
        {
            "key": "target_fruit_trees",
            "label": "Target fruit / nut trees",
            "type": "number",
            "required": False,
            "min": 20,
            "help_text": "Minimum 50 trees recommended per site.",
        },
    ],
    "estate_monitoring": [
        {
            "key": "estate_name",
            "label": "Estate / forest block name",
            "type": "text",
            "required": True,
            "placeholder": "Kumbhalgarh Wildlife Sanctuary — Block C",
        },
        {
            "key": "managing_agency",
            "label": "Managing agency",
            "type": "text",
            "required": True,
            "placeholder": "Rajasthan Forest Department",
        },
        {
            "key": "state_name",
            "label": "State / UT",
            "type": "text",
            "required": True,
            "placeholder": "Rajasthan",
        },
        {
            "key": "forest_type",
            "label": "Forest / land cover type",
            "type": "select",
            "required": True,
            "options": [
                {"value": "natural_forest", "label": "Natural forest"},
                {"value": "plantation", "label": "Planted forest / plantation"},
                {"value": "mangrove", "label": "Mangrove / coastal"},
                {"value": "urban_green", "label": "Urban green / Nagar Van"},
                {"value": "agroforestry", "label": "Agro-forestry / farm forestry"},
                {"value": "degraded_scrub", "label": "Degraded / scrub land"},
            ],
        },
        {
            "key": "total_area_ha",
            "label": "Total estate area (hectares)",
            "type": "number",
            "required": True,
            "min": 1,
            "help_text": "Total area under watch. Split large estates into 10–500 ha work-area blocks.",
        },
        {
            "key": "baseline_year",
            "label": "Monitoring baseline year",
            "type": "number",
            "required": True,
            "min": 2000,
            "max": 2030,
            "help_text": "Year from which satellite NDVI baseline is measured.",
        },
        {
            "key": "monitoring_objective",
            "label": "Primary monitoring objective",
            "type": "select",
            "required": True,
            "options": [
                {"value": "health_watch", "label": "Canopy health watch"},
                {"value": "post_planting", "label": "Post-planting watch (no tree census)"},
                {"value": "encroachment", "label": "Encroachment / integrity watch"},
                {"value": "fire_drought", "label": "Fire / drought stress watch"},
                {"value": "compliance", "label": "Scheme compliance reporting"},
            ],
        },
        {
            "key": "parent_scheme_code",
            "label": "Linked planting scheme (optional)",
            "type": "text",
            "required": False,
            "placeholder": "campa_ca",
            "help_text": "If this watch follows a CAMPA, Nagar Van, or GIM planting phase.",
        },
        {
            "key": "parent_project_ref",
            "label": "Parent project reference (optional)",
            "type": "text",
            "required": False,
            "help_text": "PCA number, Nagar Van ID, or internal project code from the planting phase.",
        },
    ],
}


def metadata_sections_for_scheme(scheme_code: str) -> list[dict[str, Any]]:
    fields = SCHEME_METADATA_FIELDS.get(scheme_code, [])
    if not fields:
        return []
    title = "Estate details" if scheme_code == "estate_monitoring" else "Scheme references"
    description = (
        "Basic estate identity and monitoring objective — no tree census required."
        if scheme_code == "estate_monitoring"
        else "Government scheme identifiers required for audit and fund convergence."
    )
    return [
        {
            "id": "scheme_refs",
            "title": title,
            "description": description,
            "fields": fields,
        }
    ]
