apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: byot
data:
  APP_ENV: "production"
  APP_NAME: "byot-api"
  APP_DEBUG: "false"
  CORS_ORIGINS: "https://byot.earth"
  AWS_REGION: "ap-south-1"
  S3_BUCKET_MEDIA: "byot-prod-media"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  namespace: byot
data:
  NEXT_PUBLIC_API_URL: "https://api.byot.earth"
