"""Portfolio-aware AI assistant for Aranyix.

When OPENAI_API_KEY or GEMINI_API_KEY is configured, answers are generated by an
LLM grounded in the user's live portfolio data. Otherwise (or if every LLM call
fails) a rule-based engine routes prompts by intent so users still get useful
portfolio answers — with mode/provider metadata so the UI can show what ran.
"""

from __future__ import annotations

import json
import re
import uuid
from dataclasses import dataclass, field
from typing import Any

import httpx
from sqlalchemy import case, func, select
from sqlalchemy.ext.asyncio import AsyncSession

from app.core.config import settings
from app.core.logging import get_logger
from app.models.alert import Alert
from app.models.bioacoustic_recording import BioacousticRecording
from app.models.plantation_fence import PlantationFence
from app.models.tree import Tree
from app.models.user import User
from app.services.carbon import CarbonInputs, estimate_carbon
from app.services.carbon.species_catalog import SPECIES_CATALOG
from app.services.data_scope import apply_owner_org_scope, apply_tree_scope

log = get_logger("assistant")

OPENAI_CHAT_URL = "https://api.openai.com/v1/chat/completions"
OPENAI_MODEL = "gpt-4o-mini"
# Prefer current Flash models; 1.5-flash / 2.0-flash are retired on AI Studio.
GEMINI_MODELS = (
    "gemini-2.5-flash",
    "gemini-3.5-flash",
    "gemini-3.6-flash",
)

SYSTEM_PROMPT = (
    "You are Aranyix, an expert environmental MRV assistant for tree plantations, "
    "carbon credits, satellite NDVI, biodiversity, weather, and compliance "
    "(IPCC, Verra, NHAI).\n"
    "Use ONLY the portfolio JSON and intelligence JSON provided.\n"
    "Rules:\n"
    "- Always finish a complete answer. Never stop mid-sentence or mid-bullet.\n"
    "- Be specific with numbers from the JSON (counts, %, tCO₂e, °C, mm rain).\n"
    "- For weather: use site_weather / forecast_summary / rain_mm_next_48h. "
    "Do not answer with alerts alone unless the user asked about alerts.\n"
    "- For health: list healthy / moderate / unhealthy counts and % from "
    "health_breakdown and pct_healthy.\n"
    "- If a field is missing, say what to do in the app (Satellite, Intelligence, "
    "Add tree).\n"
    "- Plain markdown only: short paragraphs or bullets. Bold key metrics. "
    "No nested bold-bullet glitches. Aim for 80–160 words."
)

INTENT_KEYWORDS: dict[str, tuple[str, ...]] = {
    "carbon": (
        "carbon",
        "co2",
        "co₂",
        "co2e",
        "sequest",
        "credit",
        "tco2",
        "emission",
        "offset",
        "revenue",
    ),
    "health": (
        "health",
        "disease",
        "pest",
        "sick",
        "unhealthy",
        "moderate",
        "vigor",
        "canopy",
    ),
    "satellite": (
        "satellite",
        "ndvi",
        "sentinel",
        "landsat",
        "verify",
        "verification",
        "remote sens",
    ),
    "biodiversity": (
        "biodivers",
        "bioacoustic",
        "bird",
        "fauna",
        "wildlife",
        "shannon",
        "soundscape",
        "recording",
        "species detect",
    ),
    "alerts": ("alert", "warning", "critical", "notification", "risk flag"),
    "weather": (
        "weather",
        "rain",
        "storm",
        "heat",
        "forecast",
        "drought",
        "wind",
        "thunder",
        "flood",
    ),
    "threat": (
        "threat",
        "locust",
        "hotspot",
        "early warning",
        "pest outbreak",
        "composite risk",
    ),
    "portfolio": (
        "portfolio",
        "summary",
        "overview",
        "dashboard",
        "how many",
        "total",
        "my trees",
        "registered",
        "status",
    ),
    "species": ("recommend", "which species", "what tree", "plant", "suitable", "best tree"),
}


@dataclass
class PortfolioContext:
    total_trees: int = 0
    total_carbon_kg: float = 0.0
    total_co2e_kg: float = 0.0
    annual_sequestration_kg: float = 0.0
    lifetime_credits_tco2e: float = 0.0
    estimated_revenue_usd: float = 0.0
    pct_healthy: float = 0.0
    pct_satellite_verified: float = 0.0
    health_breakdown: dict[str, int] = field(default_factory=dict)
    top_species: list[tuple[str, int]] = field(default_factory=list)
    fence_count: int = 0
    fence_names: list[str] = field(default_factory=list)
    avg_ndvi: float | None = None
    bio_recordings: int = 0
    bio_species_detected: int = 0
    bio_avg_health: float = 0.0
    bio_avg_shannon: float = 0.0
    unread_alerts: int = 0
    recent_alerts: list[dict[str, str]] = field(default_factory=list)
    focus_tree: dict[str, Any] | None = None
    intelligence: dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> dict[str, Any]:
        return {
            "total_trees": self.total_trees,
            "total_carbon_kg": round(self.total_carbon_kg, 2),
            "total_co2e_kg": round(self.total_co2e_kg, 2),
            "annual_sequestration_kg": round(self.annual_sequestration_kg, 2),
            "lifetime_credits_tco2e": round(self.lifetime_credits_tco2e, 3),
            "estimated_revenue_usd": round(self.estimated_revenue_usd, 2),
            "pct_healthy": self.pct_healthy,
            "pct_satellite_verified": self.pct_satellite_verified,
            "health_breakdown": self.health_breakdown,
            "top_species": [{"species": s, "count": c} for s, c in self.top_species],
            "fence_count": self.fence_count,
            "fence_names": self.fence_names,
            "avg_ndvi": self.avg_ndvi,
            "bio_recordings": self.bio_recordings,
            "bio_species_detected": self.bio_species_detected,
            "bio_avg_health": self.bio_avg_health,
            "bio_avg_shannon": self.bio_avg_shannon,
            "unread_alerts": self.unread_alerts,
            "recent_alerts": self.recent_alerts,
            "focus_tree": self.focus_tree,
            "intelligence": self.intelligence,
        }


def _bio_scope(stmt, user: User):
    return apply_owner_org_scope(
        stmt,
        user,
        owner_col=BioacousticRecording.owner_user_id,
        org_col=BioacousticRecording.organization_id,
    )


def _fence_scope(stmt, user: User):
    return apply_owner_org_scope(
        stmt,
        user,
        owner_col=PlantationFence.owner_user_id,
        org_col=PlantationFence.organization_id,
    )


def detect_intent(prompt: str) -> str:
    text = prompt.lower().strip()
    if is_greeting_or_smalltalk(text):
        return "greeting"
    scores: dict[str, int] = {name: 0 for name in INTENT_KEYWORDS}
    for intent, keywords in INTENT_KEYWORDS.items():
        for kw in keywords:
            if kw in text:
                scores[intent] += 1
    best = max(scores, key=scores.get)
    if scores[best] > 0:
        return best
    return "general"


GREETING_PATTERNS = (
    r"^hi\b",
    r"^hello\b",
    r"^hey\b",
    r"^hola\b",
    r"^good\s+(morning|afternoon|evening)\b",
    r"^thanks?\b",
    r"^thank\s+you\b",
    r"^help\b",
    r"^what can you do\b",
    r"^who are you\b",
)


def is_greeting_or_smalltalk(text: str) -> bool:
    normalized = re.sub(r"[^\w\s]", "", text.lower()).strip()
    if not normalized:
        return False
    if len(normalized.split()) <= 3:
        for pattern in GREETING_PATTERNS:
            if re.search(pattern, normalized):
                return True
    return False


def parse_carbon_params(prompt: str, portfolio: PortfolioContext) -> dict[str, Any]:
    text = prompt.lower()
    species = None
    for sp in SPECIES_CATALOG:
        if sp.common_name.lower() in text or sp.scientific_name.lower() in text:
            species = sp.common_name
            break
    if not species and portfolio.top_species:
        species = portfolio.top_species[0][0]

    tree_count = portfolio.total_trees or 1
    for pattern in (
        r"(\d+)\s*(?:\w+\s+)?(?:trees?|saplings?|plants?)",
        r"(?:trees?|plants?)\s*(?:of|:)?\s*(\d+)",
        r"(\d+)\s*(?:tree|plantation)",
    ):
        m = re.search(pattern, text)
        if m:
            tree_count = int(m.group(1))
            break

    years = 10
    m = re.search(r"(\d+)\s*years?", text)
    if m:
        years = int(m.group(1))

    age_years = None
    m = re.search(r"age[d]?\s*(\d+)", text)
    if m:
        age_years = float(m.group(1))

    return {
        "species": species or "Neem",
        "tree_count": tree_count,
        "years": years,
        "age_years": age_years,
    }


async def build_portfolio_context(
    db: AsyncSession,
    user: User,
    *,
    tree_id: uuid.UUID | None = None,
) -> PortfolioContext:
    ctx = PortfolioContext()

    agg = (
        select(
            func.count(Tree.id).label("total_trees"),
            func.coalesce(func.sum(Tree.current_carbon_kg), 0).label("total_carbon_kg"),
            func.coalesce(
                func.sum(case((Tree.current_health == "healthy", 1), else_=0)),
                0,
            ).label("healthy"),
            func.coalesce(
                func.sum(case((Tree.satellite_verified.is_(True), 1), else_=0)),
                0,
            ).label("sat_verified"),
        )
    )
    row = (await db.execute(await apply_tree_scope(agg, user, db))).one()
    total_trees = int(row.total_trees)
    total_carbon = float(row.total_carbon_kg or 0)
    total_co2e = total_carbon * (44.0 / 12.0)
    annual_seq = total_co2e * 0.07
    lifetime_credits = (total_co2e * 5) / 1000.0

    ctx.total_trees = total_trees
    ctx.total_carbon_kg = total_carbon
    ctx.total_co2e_kg = total_co2e
    ctx.annual_sequestration_kg = annual_seq
    ctx.lifetime_credits_tco2e = lifetime_credits
    ctx.estimated_revenue_usd = lifetime_credits * 12.0 * 0.55
    ctx.pct_healthy = round((row.healthy / total_trees * 100) if total_trees else 0, 1)
    ctx.pct_satellite_verified = round(
        (row.sat_verified / total_trees * 100) if total_trees else 0, 1
    )

    health_rows = (
        await db.execute(
            await apply_tree_scope(
                select(Tree.current_health, func.count(Tree.id)).group_by(Tree.current_health),
                user,
                db,
            )
        )
    ).all()
    ctx.health_breakdown = {h or "unknown": int(c) for h, c in health_rows}

    species_rows = (
        await db.execute(
            await apply_tree_scope(
                select(Tree.species_text, func.count(Tree.id))
                .group_by(Tree.species_text)
                .order_by(func.count(Tree.id).desc())
                .limit(5),
                user,
                db,
            )
        )
    ).all()
    ctx.top_species = [(s or "Unknown", int(c)) for s, c in species_rows]

    fences = (await db.execute(_fence_scope(select(PlantationFence), user))).scalars().all()
    ctx.fence_count = len(fences)
    ctx.fence_names = [f.name for f in fences[:5]]

    bio_rows = (await db.execute(_bio_scope(select(BioacousticRecording), user))).scalars().all()
    analyzed = [r for r in bio_rows if r.status == "analyzed"]
    ctx.bio_recordings = len(bio_rows)
    if analyzed:
        ctx.bio_avg_health = round(
            sum(float(r.bioacoustic_health_score or 0) for r in analyzed) / len(analyzed), 1
        )
        ctx.bio_avg_shannon = round(
            sum(float(r.shannon_diversity_index or 0) for r in analyzed) / len(analyzed), 3
        )
    ctx.bio_species_detected = len(
        {
            d.get("scientific_name")
            for r in analyzed
            for d in (r.species_detections or [])
            if d.get("scientific_name")
        }
    )

    alert_rows = (
        await db.execute(
            select(Alert)
            .where(Alert.user_id == user.id)
            .order_by(Alert.created_at.desc())
            .limit(5)
        )
    ).scalars().all()
    ctx.unread_alerts = sum(1 for a in alert_rows if not a.is_read)
    ctx.recent_alerts = [
        {"title": a.title, "severity": a.severity, "message": a.message[:180]}
        for a in alert_rows[:3]
    ]

    if tree_id:
        tree = (
            await db.execute(await apply_tree_scope(select(Tree).where(Tree.id == tree_id), user, db))
        ).scalar_one_or_none()
        if tree:
            ctx.focus_tree = {
                "public_code": tree.public_code,
                "species": tree.species_text,
                "health": tree.current_health,
                "carbon_kg": float(tree.current_carbon_kg or 0),
                "satellite_verified": tree.satellite_verified,
                "dbh_cm": float(tree.current_dbh_cm) if tree.current_dbh_cm else None,
                "height_m": float(tree.current_height_m) if tree.current_height_m else None,
            }

    return ctx


def _answer_portfolio(prompt: str, portfolio: PortfolioContext) -> dict[str, Any]:
    if portfolio.total_trees == 0:
        return {
            "answer": (
                "Your portfolio is empty — no trees are registered yet. "
                "Use **Add tree** or the mobile app to register your first planting, "
                "then I can summarize carbon, health, satellite verification, and biodiversity."
            ),
            "calculations": {"total_trees": 0},
            "citations": ["Aranyix portfolio registry"],
        }

    health_parts = ", ".join(
        f"{count} {status}" for status, count in sorted(portfolio.health_breakdown.items())
    )
    species_line = ", ".join(f"{name} ({count})" for name, count in portfolio.top_species[:3])
    answer = (
        f"You have **{portfolio.total_trees} trees** registered storing "
        f"**{portfolio.total_co2e_kg / 1000:.2f} tCO₂e** "
        f"(~{portfolio.annual_sequestration_kg / 1000:.2f} t/yr projected growth). "
        f"**{portfolio.pct_healthy:.0f}%** are healthy and "
        f"**{portfolio.pct_satellite_verified:.0f}%** are satellite-verified. "
        f"Health mix: {health_parts}. "
        f"Top species: {species_line or 'not tagged yet'}. "
    )
    if portfolio.fence_count:
        answer += (
            f"You monitor **{portfolio.fence_count} plantation site(s)**"
            f" ({', '.join(portfolio.fence_names[:3])}). "
        )
    if portfolio.bio_recordings:
        answer += (
            f"Bioacoustic: **{portfolio.bio_recordings} recordings**, "
            f"**{portfolio.bio_species_detected} fauna species** detected "
            f"(avg health score {portfolio.bio_avg_health}/100). "
        )
    if portfolio.unread_alerts:
        answer += f"You have **{portfolio.unread_alerts} unread alert(s)** — check the Alerts page."

    return {
        "answer": answer,
        "calculations": portfolio.to_dict(),
        "citations": ["Aranyix live portfolio", "IPCC AR6 (carbon projection)"],
    }


def _answer_carbon(prompt: str, portfolio: PortfolioContext) -> dict[str, Any]:
    params = parse_carbon_params(prompt, portfolio)
    result = estimate_carbon(
        CarbonInputs(
            species=params["species"],
            age_years=params.get("age_years"),
        )
    )
    per_tree_annual = result.annual_sequestration_kg or (result.co2e_kg * 0.07)
    years = params["years"]
    trees = params["tree_count"]
    total_t = round(per_tree_annual * trees * years / 1000.0, 2)

    if portfolio.total_trees > 0 and trees == portfolio.total_trees:
        portfolio_note = (
            f" This matches your full registered portfolio of {portfolio.total_trees} trees "
            f"(currently {portfolio.total_co2e_kg / 1000:.2f} tCO₂e stored)."
        )
    else:
        portfolio_note = ""

    answer = (
        f"For **{trees} {params['species']}** trees over **{years} years**, "
        f"the carbon engine estimates **~{total_t} tCO₂e** sequestered "
        f"(~{per_tree_annual:.1f} kg CO₂e/tree/year using {result.methodology}). "
        f"Lifetime credit potential at current tier: "
        f"**{result.lifetime_credits_tco2e:.2f} tCO₂e** "
        f"(~${result.estimated_revenue_usd:.0f} estimated revenue). "
        f"Confidence: {result.confidence:.0%}.{portfolio_note}"
    )

    return {
        "answer": answer,
        "calculations": {
            "species": params["species"],
            "tree_count": trees,
            "years": years,
            "annual_per_tree_kg_co2e": round(per_tree_annual, 2),
            "total_tco2e": total_t,
            "methodology": result.methodology,
            "confidence": result.confidence,
            "portfolio_co2e_t": round(portfolio.total_co2e_kg / 1000, 2),
        },
        "citations": ["IPCC AR6 Vol 4 Ch 4", "Chave et al. 2014", result.methodology],
    }


def _answer_health(portfolio: PortfolioContext) -> dict[str, Any]:
    if portfolio.total_trees == 0:
        return {
            "answer": "Register trees and run AI health analysis on tree photos to see health insights here.",
            "calculations": {},
            "citations": ["Aranyix tree health pipeline"],
        }

    unhealthy = portfolio.health_breakdown.get("unhealthy", 0)
    moderate = portfolio.health_breakdown.get("moderate", 0)
    healthy = portfolio.health_breakdown.get("healthy", 0)
    tips = []
    if unhealthy:
        tips.append(
            f"**{unhealthy} tree(s)** flagged unhealthy — inspect for pests, water stress, or replanting."
        )
    if moderate:
        tips.append(
            f"**{moderate} moderate** — consider balanced NPK and mulch; re-scan in 30 days."
        )
    if not tips:
        tips.append("Portfolio canopy health looks strong. Continue monthly photo checks.")

    focus = ""
    if portfolio.focus_tree:
        t = portfolio.focus_tree
        focus = (
            f" Focus tree **{t['public_code']}** ({t.get('species') or 'species TBD'}): "
            f"status **{t['health']}**, {t['carbon_kg']:.1f} kg carbon stored."
        )

    return {
        "answer": (
            f"**{healthy} healthy**, **{moderate} moderate**, **{unhealthy} unhealthy** "
            f"out of {portfolio.total_trees} trees ({portfolio.pct_healthy:.0f}% healthy). "
            + " ".join(tips)
            + focus
        ),
        "calculations": {
            "health_breakdown": portfolio.health_breakdown,
            "pct_healthy": portfolio.pct_healthy,
        },
        "citations": ["Aranyix AI health classification", "Field scouting recommended"],
    }


def _answer_satellite(portfolio: PortfolioContext) -> dict[str, Any]:
    verified = round(portfolio.pct_satellite_verified, 1)
    pending = max(0, portfolio.total_trees - round(portfolio.total_trees * verified / 100))
    answer = (
        f"**{verified}%** of your trees ({portfolio.total_trees - pending} of {portfolio.total_trees}) "
        f"are satellite-verified. "
    )
    if portfolio.fence_count:
        answer += (
            f"You have **{portfolio.fence_count} plantation fence(s)** configured for NDVI monitoring. "
            "Open the Satellite page to run Sentinel-2 scans and track canopy stress."
        )
    else:
        answer += (
            "No plantation fences yet — draw a site boundary on the Satellite page "
            "to enable NDVI time-series and change detection."
        )
    return {
        "answer": answer,
        "calculations": {
            "pct_satellite_verified": verified,
            "fence_count": portfolio.fence_count,
            "avg_ndvi": portfolio.avg_ndvi,
        },
        "citations": ["Sentinel-2 NDVI", "Aranyix satellite MRV"],
    }


def _answer_biodiversity(portfolio: PortfolioContext) -> dict[str, Any]:
    if portfolio.bio_recordings == 0:
        return {
            "answer": (
                "No bioacoustic recordings yet. Record a 30–60 second soundscape "
                "on the Biodiversity page to detect birds, insects, and amphibians near your plantation."
            ),
            "calculations": {},
            "citations": ["Aranyix bioacoustic engine"],
        }
    return {
        "answer": (
            f"From **{portfolio.bio_recordings} soundscape recording(s)**, "
            f"**{portfolio.bio_species_detected} fauna species** were detected. "
            f"Average biodiversity health score: **{portfolio.bio_avg_health}/100**. "
            f"Shannon diversity index (H′): **{portfolio.bio_avg_shannon}**. "
            "Record at dawn or dusk for best avian detection rates."
        ),
        "calculations": {
            "bio_recordings": portfolio.bio_recordings,
            "bio_species_detected": portfolio.bio_species_detected,
            "bio_avg_health": portfolio.bio_avg_health,
            "bio_avg_shannon": portfolio.bio_avg_shannon,
        },
        "citations": ["Bioacoustic diversity indices", "GBIF / IUCN enrichment"],
    }


def _answer_alerts(portfolio: PortfolioContext) -> dict[str, Any]:
    intel = portfolio.intelligence or {}
    weather_count = intel.get("weather_alert_count", 0)
    pest_high = intel.get("pest_high_count", 0)
    if weather_count or pest_high:
        lines = [
            f"Intelligence hub: **{weather_count} weather alert(s)** and "
            f"**{pest_high} high pest-risk site(s)** across your portfolio."
        ]
        for alert in intel.get("weather_alerts", [])[:3]:
            lines.append(
                f"- Weather [{alert.get('alert', {}).get('severity', 'info').upper()}] "
                f"{alert.get('work_area_name', 'site')}: "
                f"{alert.get('alert', {}).get('title', 'alert')}"
            )
        for hotspot in intel.get("pest_hotspots", [])[:3]:
            lines.append(
                f"- Pest hotspot **{hotspot.get('work_area_name', 'site')}** "
                f"(risk: {hotspot.get('composite_risk', 'unknown')})"
            )
        if portfolio.recent_alerts:
            lines.append("")
            lines.append(f"Also **{portfolio.unread_alerts} unread** in-app alert(s).")
        return {
            "answer": "\n".join(lines),
            "calculations": {
                "weather_alert_count": weather_count,
                "pest_high_count": pest_high,
                "unread_alerts": portfolio.unread_alerts,
            },
            "citations": ["Aranyix intelligence hub", "Open-Meteo forecasts"],
        }

    if not portfolio.recent_alerts:
        return {
            "answer": "No active alerts — your portfolio looks clear. Satellite health notifications can be enabled on the Alerts page.",
            "calculations": {"unread_alerts": 0},
            "citations": ["Aranyix alert service"],
        }
    lines = [f"**{portfolio.unread_alerts} unread** alert(s). Recent:"]
    for a in portfolio.recent_alerts:
        lines.append(f"- [{a['severity'].upper()}] {a['title']}: {a['message']}")
    return {
        "answer": "\n".join(lines),
        "calculations": {"unread_alerts": portfolio.unread_alerts},
        "citations": ["Aranyix satellite & health alerts"],
    }


def _answer_weather(portfolio: PortfolioContext) -> dict[str, Any]:
    intel = portfolio.intelligence or {}
    sites = intel.get("site_weather") or []
    alerts = intel.get("weather_alerts", [])
    lines: list[str] = []

    if sites:
        lines.append(f"**Weather for {len(sites)} plantation site(s):**")
        for site in sites[:5]:
            name = site.get("work_area_name") or "Site"
            forecast = site.get("forecast_summary") or "Forecast unavailable."
            rain = site.get("rain_mm_next_48h")
            rain_bit = f" Rain next 48h: {float(rain):.0f} mm." if rain is not None else ""
            lines.append(f"- **{name}**: {forecast}{rain_bit}")
    else:
        lines.append(
            "No plantation sites with forecasts yet. Draw a fence on the **Satellite** "
            "page or open **Intelligence** so Open-Meteo can load site weather."
        )

    if alerts:
        lines.append("")
        lines.append(f"**{len(alerts)} active weather alert(s):**")
        for item in alerts[:3]:
            alert = item.get("alert", {})
            lines.append(
                f"- **{item.get('work_area_name', 'Site')}**: "
                f"[{alert.get('severity', 'info').upper()}] {alert.get('title', 'Alert')}"
            )
    elif sites:
        lines.append("")
        lines.append("No severe weather alerts right now.")

    return {
        "answer": "\n".join(lines),
        "calculations": {
            "weather_alert_count": intel.get("weather_alert_count", len(alerts)),
            "sites_with_forecast": len(sites),
        },
        "citations": ["Open-Meteo", "Aranyix intelligence hub"],
    }


def _answer_threat(portfolio: PortfolioContext) -> dict[str, Any]:
    intel = portfolio.intelligence or {}
    risk = intel.get("highest_risk", "low")
    hotspots = intel.get("pest_hotspots", [])
    warnings = intel.get("early_warnings", [])
    lines = [f"Portfolio composite risk is **{risk}**."]
    if hotspots:
        lines.append(f"**{len(hotspots)} pest/weather hotspot(s)**:")
        for h in hotspots[:5]:
            lines.append(
                f"- **{h.get('work_area_name', 'Site')}** — risk {h.get('composite_risk', '?')}, "
                f"rain next 48h: {h.get('rain_mm_next_48h', 0):.0f} mm"
            )
    if warnings:
        lines.append("Early warnings:")
        for w in warnings[:3]:
            lines.append(f"- [{w.get('severity', 'info').upper()}] {w.get('title', 'Warning')}")
    if not hotspots and not warnings:
        lines.append("No elevated threat signals — continue routine monitoring.")
    return {
        "answer": "\n".join(lines),
        "calculations": {
            "highest_risk": risk,
            "pest_high_count": intel.get("pest_high_count", 0),
        },
        "citations": ["Aranyix threat watch", "Pest intel v2", "Locust corridor model"],
    }


def _answer_species(prompt: str, portfolio: PortfolioContext) -> dict[str, Any]:
    text = prompt.lower()
    if "dry" in text or "drought" in text:
        rec = ["Neem", "Amla", "Banyan"]
        reason = "drought-tolerant natives with strong survival in water-stressed sites"
    elif "highway" in text or "road" in text:
        rec = ["Peepal", "Gulmohar", "Neem"]
        reason = "hardy species used in linear infrastructure greening (NHAI-style planting)"
    elif "carbon" in text or "credit" in text:
        rec = ["Teak", "Mango", "Neem"]
        reason = "well-documented allometric curves and IPCC-compatible growth assumptions"
    else:
        rec = ["Neem", "Mango", "Amla", "Bamboo"]
        reason = "versatile species with strong catalog coverage in the Aranyix carbon engine"

    answer = (
        f"For your question, consider **{', '.join(rec)}** — {reason}. "
        f"Your portfolio already includes: "
        f"{', '.join(s for s, _ in portfolio.top_species[:3]) or 'no species tagged yet'}. "
        "Register with GPS + photos so species-specific carbon and health models apply."
    )
    return {
        "answer": answer,
        "calculations": {"recommended_species": rec},
        "citations": ["Aranyix species catalog", "IPCC AR6 allometrics"],
    }


def _answer_greeting(portfolio: PortfolioContext, user_name: str | None = None) -> dict[str, Any]:
    name = (user_name or "there").split()[0]
    if portfolio.total_trees == 0:
        return {
            "answer": (
                f"Hello {name}! I'm your Aranyix environmental analyst. "
                "Your portfolio is empty so far — register your first tree and I can "
                "summarize carbon, health, satellite NDVI, biodiversity, and alerts for you."
            ),
            "calculations": {},
            "citations": [],
        }

    lines = [
        f"Hello {name}! I'm your Aranyix environmental analyst. Here's your live snapshot:",
        "",
        f"• {portfolio.total_trees} trees registered",
        f"• {portfolio.total_co2e_kg / 1000:.2f} tCO₂e stored",
        f"• {portfolio.pct_healthy:.0f}% healthy · {portfolio.pct_satellite_verified:.0f}% satellite-verified",
    ]
    if portfolio.bio_recordings:
        lines.append(
            f"• {portfolio.bio_species_detected} fauna species detected across "
            f"{portfolio.bio_recordings} bioacoustic recordings"
        )
    if portfolio.unread_alerts:
        lines.append(f"• {portfolio.unread_alerts} unread alert(s) need attention")
    lines.extend(
        [
            "",
            "Ask about carbon projections, tree health, satellite NDVI, biodiversity, "
            "alerts, or say **portfolio summary** for the full picture.",
        ]
    )
    return {
        "answer": "\n".join(lines),
        "calculations": {},
        "citations": [],
    }


def _answer_general(prompt: str, portfolio: PortfolioContext) -> dict[str, Any]:
    if portfolio.total_trees == 0:
        return _answer_portfolio(prompt, portfolio)
    # Short or vague prompts get a concise portfolio summary instead of a help menu.
    if len(prompt.strip()) < 40:
        return _answer_portfolio(prompt, portfolio)
    return {
        "answer": (
            f"I can help with your **{portfolio.total_trees} trees** "
            f"({portfolio.total_co2e_kg / 1000:.2f} tCO₂e stored). "
            "Try asking about: **carbon projections**, **tree health**, **satellite NDVI**, "
            "**biodiversity recordings**, **alerts**, or a **portfolio summary**."
        ),
        "calculations": {},
        "citations": ["Aranyix assistant"],
    }


def _sanitize_response(out: dict[str, Any]) -> dict[str, Any]:
    """Remove internal metadata before sending to clients."""
    calcs = dict(out.get("calculations") or {})
    for key in ("intent", "mode", "portfolio", "provider", "llm_error"):
        calcs.pop(key, None)
    out["calculations"] = calcs
    out.setdefault("mode", "rules")
    out.setdefault("provider", "rules")
    out.setdefault("llm_error", None)
    return out


def _user_prompt_payload(
    prompt: str,
    portfolio: PortfolioContext,
    intelligence: dict[str, Any] | None,
) -> str:
    user_content = (
        f"User question:\n{prompt}\n\n"
        f"Live portfolio JSON:\n{json.dumps(portfolio.to_dict(), indent=2)}"
    )
    if intelligence:
        user_content += f"\n\nIntelligence hub JSON:\n{json.dumps(intelligence, indent=2)}"
    return user_content


def _looks_truncated_or_thin(text: str) -> bool:
    """Detect incomplete LLM answers (cut mid-markdown / mid-sentence)."""
    t = (text or "").rstrip()
    if len(t) < 48:
        return True
    if t.count("**") % 2 == 1:
        return True
    if t.endswith(("**", "*", ":", "-", "—", ",", "(")):
        return True
    # Started a health/weather list but never finished a number line
    lower = t.lower()
    return (
        "as follows" in lower
        and "healthy" in lower
        and not any(ch.isdigit() for ch in t)
    )


def _short_llm_error(exc: Exception) -> str:
    """Compact, non-secret error for operators / UI diagnostics."""
    text = str(exc).strip() or exc.__class__.__name__
    # Prefer HTTP status from httpx when present
    response = getattr(exc, "response", None)
    if response is not None:
        status = getattr(response, "status_code", None)
        body = ""
        try:
            body = (response.text or "")[:180]
        except Exception:
            body = ""
        if status:
            return f"HTTP {status}" + (f": {body}" if body else "")
    return text[:220]


def answer_with_rules(
    prompt: str,
    portfolio: PortfolioContext,
    *,
    user_name: str | None = None,
    llm_error: str | None = None,
) -> dict[str, Any]:
    intent = detect_intent(prompt)
    handlers = {
        "greeting": lambda: _answer_greeting(portfolio, user_name),
        "portfolio": lambda: _answer_portfolio(prompt, portfolio),
        "carbon": lambda: _answer_carbon(prompt, portfolio),
        "health": lambda: _answer_health(portfolio),
        "satellite": lambda: _answer_satellite(portfolio),
        "biodiversity": lambda: _answer_biodiversity(portfolio),
        "alerts": lambda: _answer_alerts(portfolio),
        "weather": lambda: _answer_weather(portfolio),
        "threat": lambda: _answer_threat(portfolio),
        "species": lambda: _answer_species(prompt, portfolio),
        "general": lambda: _answer_general(prompt, portfolio),
    }
    out = _sanitize_response(handlers[intent]())
    out["mode"] = "rules"
    out["provider"] = "rules"
    out["llm_error"] = llm_error
    return out


async def answer_with_openai(
    prompt: str,
    portfolio: PortfolioContext,
    *,
    intelligence: dict[str, Any] | None = None,
) -> tuple[dict[str, Any] | None, str | None]:
    """Return (answer, error). error is set when the key exists but the call failed."""
    api_key = settings.openai_api_key
    if not api_key:
        return None, None

    user_content = _user_prompt_payload(prompt, portfolio, intelligence)

    try:
        async with httpx.AsyncClient(timeout=45.0) as client:
            resp = await client.post(
                OPENAI_CHAT_URL,
                headers={
                    "Authorization": f"Bearer {api_key}",
                    "Content-Type": "application/json",
                },
                json={
                    "model": OPENAI_MODEL,
                    "temperature": 0.45,
                    "max_tokens": 1200,
                    "messages": [
                        {"role": "system", "content": SYSTEM_PROMPT},
                        {"role": "user", "content": user_content},
                    ],
                },
            )
            resp.raise_for_status()
            text = resp.json()["choices"][0]["message"]["content"].strip()
            if text and not _looks_truncated_or_thin(text):
                return (
                    _sanitize_response(
                        {
                            "answer": text[:3500],
                            "calculations": {},
                            "citations": ["Aranyix live portfolio", "OpenAI analysis"],
                            "mode": "llm",
                            "provider": "openai",
                            "llm_error": None,
                        }
                    ),
                    None,
                )
            if text:
                return None, "OpenAI returned a truncated or incomplete answer"
            return None, "OpenAI returned an empty response"
    except Exception as exc:
        err = _short_llm_error(exc)
        log.warning("assistant.openai_failed", error=err)
        return None, f"OpenAI: {err}"


async def answer_with_gemini(
    prompt: str,
    portfolio: PortfolioContext,
    *,
    intelligence: dict[str, Any] | None = None,
) -> tuple[dict[str, Any] | None, str | None]:
    """Return (answer, error). error is set when the key exists but the call failed."""
    api_key = settings.gemini_api_key
    if not api_key:
        return None, None

    user_content = _user_prompt_payload(prompt, portfolio, intelligence)
    last_err: str | None = None

    async with httpx.AsyncClient(timeout=45.0) as client:
        for model in GEMINI_MODELS:
            url = (
                "https://generativelanguage.googleapis.com/v1beta/models/"
                f"{model}:generateContent"
            )
            try:
                resp = await client.post(
                    url,
                    params={"key": api_key},
                    json={
                        "system_instruction": {"parts": [{"text": SYSTEM_PROMPT}]},
                        "contents": [{"role": "user", "parts": [{"text": user_content}]}],
                        "generationConfig": {
                            "temperature": 0.35,
                            "maxOutputTokens": 1200,
                        },
                    },
                )
                resp.raise_for_status()
                body = resp.json()
                text = body["candidates"][0]["content"]["parts"][0]["text"].strip()
                if text and not _looks_truncated_or_thin(text):
                    return (
                        _sanitize_response(
                            {
                                "answer": text[:3500],
                                "calculations": {},
                                "citations": [
                                    "Aranyix live portfolio",
                                    f"Gemini ({model})",
                                ],
                                "mode": "llm",
                                "provider": "gemini",
                                "llm_error": None,
                            }
                        ),
                        None,
                    )
                if text:
                    last_err = f"Gemini/{model}: truncated or incomplete answer"
                    log.warning("assistant.gemini_thin_answer", model=model, preview=text[:120])
                    continue
                last_err = f"Gemini/{model}: empty response"
            except Exception as exc:
                last_err = f"Gemini/{model}: {_short_llm_error(exc)}"
                log.warning("assistant.gemini_failed", model=model, error=last_err)
                # Try next model on 404/NOT_FOUND; stop early on auth/quota.
                status = getattr(getattr(exc, "response", None), "status_code", None)
                if status in {401, 403, 429}:
                    break

    return None, last_err or "Gemini returned an empty response"


async def run_assistant(
    prompt: str,
    user: User,
    db: AsyncSession,
    *,
    tree_id: uuid.UUID | None = None,
) -> dict[str, Any]:
    portfolio = await build_portfolio_context(db, user, tree_id=tree_id)
    intelligence: dict[str, Any] = {}
    try:
        from app.services.intelligence.summary import (
            build_intelligence_summary,
            intelligence_context_for_assistant,
        )

        summary = await build_intelligence_summary(db, user, site_limit=10, fast=True)
        intelligence = intelligence_context_for_assistant(summary)
        portfolio.intelligence = intelligence
    except Exception as exc:
        log.warning("assistant.intelligence_context_failed", error=str(exc))

    llm_errors: list[str] = []
    openai_out, openai_err = await answer_with_openai(
        prompt, portfolio, intelligence=intelligence or None
    )
    if openai_out:
        return openai_out
    if openai_err:
        llm_errors.append(openai_err)

    gemini_out, gemini_err = await answer_with_gemini(
        prompt, portfolio, intelligence=intelligence or None
    )
    if gemini_out:
        return gemini_out
    if gemini_err:
        llm_errors.append(gemini_err)

    if not settings.openai_api_key and not settings.gemini_api_key:
        llm_errors.append("No OPENAI_API_KEY or GEMINI_API_KEY configured on the API")

    return answer_with_rules(
        prompt,
        portfolio,
        user_name=user.full_name,
        llm_error="; ".join(llm_errors) if llm_errors else None,
    )
