"""Homepage reports catalog for CMS defaults."""

from __future__ import annotations

from typing import Any

HOME_REPORT_ITEMS: list[dict[str, Any]] = [
    {
        "category": "carbon",
        "tag": "GHG Protocol",
        "title": "GHG land-sector inventory",
        "description": "Land-sector removals and emissions structured for corporate GHG Protocol reporting.",
        "formats": "PDF · XLSX",
        "featured": True,
        "evidence_hint": "Org + project roll-up",
        "action": "generate",
        "accent": "#15803d",
    },
    {
        "category": "carbon",
        "tag": "Carbon",
        "title": "Carbon stock & tree absorption",
        "description": "Modelled biomass and CO₂e removals by species and plot with IPCC-aligned defaults.",
        "formats": "PDF · XLSX",
        "featured": True,
        "evidence_hint": "Per plantation site",
        "action": "generate",
        "accent": "#166534",
    },
    {
        "category": "carbon",
        "tag": "Methane",
        "title": "Site methane & atmospheric GHG",
        "description": "TROPOMI-fused CH₄ context overlaid on project work areas with dispersion and fusion review.",
        "formats": "PDF · XLSX",
        "evidence_hint": "Satellite + source fusion",
        "action": "generate",
        "accent": "#0e7490",
    },
    {
        "category": "carbon",
        "tag": "VM0047",
        "title": "Carbon credit ledger",
        "description": "Serial tracking, verifier sampling, and NPRT buffer assessments per project.",
        "formats": "PDF · XLSX",
        "action": "generate",
        "accent": "#14532d",
    },
    {
        "category": "carbon",
        "tag": "ISO 14064-1",
        "title": "Organizational GHG inventory",
        "description": "Org-level inventory export complementing ISO 14064-2 project quantification reports.",
        "formats": "JSON · XLSX · ZIP",
        "action": "generate",
        "accent": "#1e3a5f",
    },
    {
        "category": "biodiversity",
        "tag": "Soundscape",
        "title": "Biodiversity soundscape report",
        "description": "BirdNET species detections, acoustic richness scores, and seasonal trends for a fenced site.",
        "formats": "PDF · XLSX",
        "featured": True,
        "evidence_hint": "Bioacoustic engine",
        "action": "generate",
        "accent": "#0d9488",
    },
    {
        "category": "biodiversity",
        "tag": "Darwin Core",
        "title": "Darwin Core occurrence pack",
        "description": "Standardized species occurrence archive for biodiversity partners and scientific reuse.",
        "formats": "ZIP · JSON",
        "action": "download",
        "accent": "#0f766e",
    },
    {
        "category": "biodiversity",
        "tag": "Biodiversity",
        "title": "Biodiversity evidence summary",
        "description": "Species richness, habitat signals, and acoustic health for a plantation fence boundary.",
        "formats": "PDF · XLSX",
        "action": "generate",
        "accent": "#115e59",
    },
    {
        "category": "biodiversity",
        "tag": "ESG",
        "title": "ESG nature narrative",
        "description": "Combined biodiversity, NDVI habitat, and acoustic richness narrative for stakeholders.",
        "formats": "PDF · XLSX",
        "action": "generate",
        "accent": "#134e4a",
    },
    {
        "category": "disclosure",
        "tag": "TNFD",
        "title": "TNFD LEAP disclosure",
        "description": "Locate–Evaluate–Assess–Prepare narrative from satellite and bioacoustic layers.",
        "formats": "PDF · XLSX",
        "featured": True,
        "action": "generate",
        "accent": "#3f6212",
    },
    {
        "category": "disclosure",
        "tag": "Green Credit",
        "title": "Green Credit India pack",
        "description": "MoEFCC Green Credit Programme evidence with land bank and survival KPIs.",
        "formats": "PDF · XLSX",
        "action": "generate",
        "accent": "#4d7c0f",
    },
    {
        "category": "disclosure",
        "tag": "REDD+",
        "title": "REDD+ MRV report",
        "description": "Baseline, permanence, and leakage sections structured for REDD+ program review.",
        "formats": "PDF · XLSX",
        "action": "generate",
        "accent": "#365314",
    },
    {
        "category": "disclosure",
        "tag": "Paris / NDC",
        "title": "Paris Agreement traceability",
        "description": "NDC-aligned planting ledger export with Article 6 cooperative-approaches context.",
        "formats": "PDF · XLSX",
        "action": "generate",
        "accent": "#1e3a5f",
    },
    {
        "category": "disclosure",
        "tag": "Gold Standard",
        "title": "Gold Standard LUF report",
        "description": "Land Use & Forests framework-mapped PDF and Excel for voluntary verification prep.",
        "formats": "PDF · XLSX",
        "action": "generate",
        "accent": "#854d0e",
    },
    {
        "category": "compliance",
        "tag": "BRSR",
        "title": "BRSR assurance pack",
        "description": "SEBI-aligned Principle 6 export with plantation KPIs and evidence references.",
        "formats": "PDF · XLSX",
        "featured": True,
        "action": "generate",
        "accent": "#14532d",
    },
    {
        "category": "compliance",
        "tag": "ISO 14064-2",
        "title": "ISO 14064-2 project report",
        "description": "Project boundary, monitoring plan, and quantification sections pre-structured.",
        "formats": "PDF · XLSX",
        "action": "generate",
        "accent": "#166534",
    },
    {
        "category": "compliance",
        "tag": "ETF / BTR",
        "title": "National inventory handoff",
        "description": "Org-level IPCC activity tables with leakage, buffer, and SAR integrity flags for ETF/BTR pilots.",
        "formats": "CSV · XLSX",
        "action": "download",
        "accent": "#1e3a5f",
    },
    {
        "category": "compliance",
        "tag": "SBTi FLAG",
        "title": "FLAG land-sector worksheet",
        "description": "Land-related removals vs target boundary linked to VM0047 and GHG exports.",
        "formats": "XLSX",
        "action": "download",
        "accent": "#4c1d95",
    },
    {
        "category": "compliance",
        "tag": "EUDR",
        "title": "Supplier geo due diligence",
        "description": "WGS84 coordinate pack with BRSR value-chain linkage for corporate buyers.",
        "formats": "XLSX · ZIP",
        "action": "download",
        "accent": "#44403c",
    },
    {
        "category": "compliance",
        "tag": "Inventory",
        "title": "Geo-tagged tree inventory",
        "description": "Species, survival, chainage, and geotag completeness for compliance packs.",
        "formats": "PDF · XLSX",
        "action": "generate",
        "accent": "#3f6212",
    },
    {
        "category": "compliance",
        "tag": "Evidence",
        "title": "Signed evidence bundle",
        "description": "Tamper-evident ZIP with Ed25519 audit-chain verification for third-party review.",
        "formats": "ZIP",
        "signed": True,
        "action": "download",
        "accent": "#14532d",
    },
]

for item in HOME_REPORT_ITEMS:
    item.setdefault("href", "/auth?mode=signin&next=/reports")
    item.setdefault("status", "live")
